### ISSUE TITLE
Find a guide should filter all guides not just getting started ones

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/sagan#1001]
I think it would be great if https://spring.io/guides could be modified to make the "Find a guide" textbox filtering all guides not just getting started ones. I found currently behavior pretty confusing while trying to reach the Kotlin tutorial:
 - Find a guide textbox position and label makes not obvious that it filters only getting started ones
 - I type Kotlin
 - I see "No result found"
 - I have to scroll down to see the Kotlin tutorial

**Comment by bclozel** [comment]
Closing in favour of #1033
