### ISSUE TITLE
Gradle Build Hanging

### ISSUE THREAD

**Issue by dkendall100** [spring-io/sagan#1005]
The Gradle build process when attempting to run spring project encounters deadlock. Any help or suggestions are appreciated!

### My Setup

**IDE:** IntelliJ 2020.2
**JDK:** JDK 8
**Operating System:** macOS Mojave 10.14.6 (18G6020)
**Branch:** master

### Attempted Fixes
1. clear `.gradle` folder in home directory and project folder
2. Invalidated caches within IntelliJ IDE
3. Rebooted system
4. Running with `sudo`

None of the actions helped. 

### Information
`./gradlew bootRun --debug` yields the following output [log.txt](https://github.com/spring-io/sagan/files/5462998/log.txt) 

`jstack 38832` yields the following process stack trace [jstack_out.txt](https://github.com/spring-io/sagan/files/5463002/jstack_out.txt)
```
38832 ttys000    0:05.18 /usr/bin/java -Xdock:name=Gradle -Xdock:icon=/Users/dustink/Projects/opensource/java/sagan/media/gradle.icns -Dorg.gradle.appname=gradlew -classpath /Users/dustink/Projects/opensource/java/sagan/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain bootrun --debug
```

`./gradlew check` yields [check.txt](https://github.com/spring-io/sagan/files/5463015/check.txt)

**Comment by bclozel** [comment]
If you want to run one of the applications hosted in this repository, you'll [need to follow the instructions here](https://github.com/spring-io/sagan/wiki/Run-the-site-locally).

You should probably be running `./gradlew :sagan-site:bootRun` and `./gradlew :sagan-renderer:bootRun` in different terminals.
