### ISSUE TITLE
Show listed the Spring Data Commons project within the Spring Data page

### ISSUE THREAD

**Issue by manueljordan** [spring-io/sagan#1006]
Hello Developers

Why in the [Spring Data](https://spring.io/projects/spring-data) project page does not appear listed the `Spring Data Commons` project? It to let me get access to the `Reference Documentation` and `Javadocs` - such as: 

* [Spring Data Commons - Reference Documentation](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#reference)
* [Spring Data Core #.#.# API](https://docs.spring.io/spring-data/commons/docs/current/api/) (about this name, see in the bottom the observation section)

I got access to that URLs acceding to `Spring Data JPA` project and playing through the URL in the Web Browser
I mean:

![01](https://user-images.githubusercontent.com/2552795/98382955-e13bdc80-2019-11eb-899c-22590842902c.png)

![02](https://user-images.githubusercontent.com/2552795/98382990-e9941780-2019-11eb-82a3-c299249634d5.png)

**Observation**: The project is named `Spring Data Commons`, so why in the Javadoc appears the `Spring Data Core` term instead?. I would be confuse.

![03](https://user-images.githubusercontent.com/2552795/98383171-24964b00-201a-11eb-8995-7212d8f1f49b.png)

I did realise later that exists other approach: the [Spring Data](https://spring.io/projects/spring-data) has the `Main modules` section

![04](https://user-images.githubusercontent.com/2552795/98384397-b94d7880-201b-11eb-8938-fdd9e9e4fa2a.png)

But it directs to the Github project and then I must navigate to the links desired. 

![05](https://user-images.githubusercontent.com/2552795/98384501-d8e4a100-201b-11eb-8d60-0d6eddea85a2.png)

If `Spring Data Commons` can be added how the rest of the sub projects in the menu show in the left would be nice. 

![06](https://user-images.githubusercontent.com/2552795/98384890-590b0680-201c-11eb-800f-bb14d0bf40f4.png)

It to get a most straight access such as the others projects and keeping the same structure.

![07](https://user-images.githubusercontent.com/2552795/98384944-6627f580-201c-11eb-95f6-58dd77460881.png)

Thank You.

**Comment by bclozel** [comment]
I think it's up to the Spring Data team to decide if they'd like to display spring-data-commons as a standalone project on spring.io or if they'd rather rely on cross-linking for that. Paging @mp911de

**Comment by mp911de** [comment]
We'd rather not include Spring Data Commons as project page because it's not a standalone-project that is intended for direct usage. Rather, you get the dependency transitively. I agree that getting to the Javadocs directly isn't trivial if you don't know the documentation structure.

Reference-documentation-wise, Commons ships with documentation fragments that are included by almost every Spring Data module.

I'm wondering whether it would make sense to link to the Commons documentation from within the general [Spring Data project page](https://spring.io/projects/spring-data#learn).

**Comment by manueljordan** [comment]
Hello

```
We'd rather not include Spring Data Commons as project page because it's not a standalone-project that is intended for direct usage. Rather, you get the dependency transitively
```
I am agree in some way, but I would expect (for a newcomer) see the project listed how a project and in its page showing a special note indicating that it is not a standalone-project, and highlighting that the page is available for simplicity of documentation access. Therefore below of that note show the two links, for  Reference and Javadoc.

IMHO it is the most simple and straight approach

**Comment by mp911de** [comment]
That's fixed now via https://github.com/spring-projects/spring-data-dev-tools/issues/167. I think we can close this ticket here.

**Comment by bclozel** [comment]
Thanks @mp911de !
