### ISSUE TITLE
Secured pages showing 500 error rather than redirecting to login

### ISSUE THREAD

**Issue by spencergibb** [spring-io/sagan#1007]
https://spring.io/admin/blog/xyz/edit

![image](https://user-images.githubusercontent.com/594085/98587934-dfcc1780-2298-11eb-982c-8b19dffe3a3e.png)

Going to https://spring.io/admin and logging in and the clicking the link works.

**Comment by spencergibb** [comment]
Thanks @bclozel!

**Comment by bclozel** [comment]
Thanks for the heads up, the fix is live now.
