### ISSUE TITLE
Allow {version} in the URLS for documentation and javadoc at admin/projects/{project}/releases

### ISSUE THREAD

**Issue by rwinch** [spring-io/sagan#1023]
Previously, we were able to use a variable `{version}` in the URLs for the documentation and Javadoc. This made updating the release version much easier. If combined with gh-1022 that would mean we could just change the version and save to perform a release.

**Comment by spencergibb** [comment]
It's what we use in spring cloud `https://docs.spring.io/spring-cloud-commons/docs/{version}/reference/html/`

**Comment by bclozel** [comment]
Thanks @spencergibb !
Indeed the `{version}` templated variable was working but this was not documented. I've pushed a change that pre-fills the documentation URLs with sensible defaults for most projects (using the project ID and the `{version}`) so this should make things easier.
