### ISSUE TITLE
Can't clone the project?

### ISSUE THREAD

**Issue by MikeDub1** [spring-io/sagan#1027]
Hey guys! I am a newbie in Spring and I am looking for experience in using this framework. When I tried cloning this project however, I get this error from GitBash: `Please make sure you have the correct access rights
and the repository exists.` Can someone help me out please?

**Comment by bclozel** [comment]
I don't really know how to help here, the error message doesn't give enough information.
Did you try with [the wiki instructions](https://github.com/spring-io/sagan/wiki/Get-the-source)?

**Comment by tvuchova** [comment]
What are you using for clone it https or ssh? Try to use HTTPS instead SSH while taking clone from GIT

**Comment by MikeDub1** [comment]
> I don't really know how to help here, the error message doesn't give enough information.
> Did you try with [the wiki instructions](https://github.com/spring-io/sagan/wiki/Get-the-source)?

Hey, I did read the instructions. As a matter of fact, that is how I ended up with the error. I simply forked the project and I was able to clone that instead.
