### ISSUE TITLE
Gradle source compatibility

### ISSUE THREAD

**Issue by Plat-26** [spring-io/sagan#1039]
The project wiki defines JDK 8 as the compatible version but  sagan-site\build.gradle and sagan-renderer\build.gradle files have sourceCompacibility=11. Using that configuration caused build failures and I had to change the value to 1.8 before passing the build. Perhaps the Gradle files should be updated in this way.

**Comment by bclozel** [comment]
We probably need to update the wiki.
How is the build failing with JDK11?

**Comment by bclozel** [comment]
How? Could you provide the error?
