### ISSUE TITLE
Sort support period lists and graphs so most recent are first

### ISSUE THREAD

**Issue by dsyer** [spring-io/sagan#1044]
The top of the tables and graphs should be the most recent versions IMO - we don't want users to have to scan to the bottom to find the latest, recommended release.

**Comment by bclozel** [comment]
Maybe a matter of preference? I haven't seen any other project adopt this opinion, though.

![Screenshot 2021-11-19 at 10 42 02](https://user-images.githubusercontent.com/103264/142601236-7faa1472-3a3f-42c0-9a87-2068efeffff9.png)

![Screenshot 2021-11-19 at 10 41 52](https://user-images.githubusercontent.com/103264/142601249-5b9cddfd-b4af-4731-a3b3-20f16f12fb73.png)

What do you think @oodamien ?

**Comment by oodamien** [comment]
Make sense to have the last version on top.
