### ISSUE TITLE
Invalid link in Spring for Apache Kafka

### ISSUE THREAD

**Issue by chanhyeong** [spring-io/sagan#1065]
There is a invalid link in bottom of [Spring for Apache Kafka](https://spring.io/projects/spring-kafka)

I think the doc was migrated from `Core Features` to `Messaging`.

- invalid: https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.messaging.kafka
- valid: https://docs.spring.io/spring-boot/docs/current/reference/html/messaging.html#messaging.kafka

---

There are more invalid links in kafka docs too.

- invalid: https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#messaging.kafka.additional-properties
- valid: https://docs.spring.io/spring-boot/docs/current/reference/html/messaging.html#messaging.kafka.additional-properties

**Comment by bclozel** [comment]
@garyrussell @artembilan Could you have a look?

**Comment by garyrussell** [comment]
@chanhyeong Thanks for reporting.

I fixed the link on the project page; please raise an issue against Spring Boot for the incorrect link(s) in the docs themselves.

**Comment by bclozel** [comment]
@garyrussell Are you sure that those links are in the Spring Boot docs themselves? @chanhyeong reported them as

> There are more invalid links in kafka docs too.

I'm seeing three invalid links to the Spring Boot docs in the Kafka docs:
* https://docs.spring.io/spring-kafka/docs/current-SNAPSHOT/reference/html/#getting-started
* https://docs.spring.io/spring-kafka/docs/current-SNAPSHOT/reference/html/#json-serde
* https://docs.spring.io/spring-kafka/docs/2.5.x-SNAPSHOT/reference/html/#serdes-mapping-types

@chanhyeong Can you share where those links are? Could you give us a URL?

**Comment by garyrussell** [comment]
@bclozel Thanks; I'll fix those, but we have no links to a URL containing `additional-properties` in our docs (hence I assumed it was a reference to the boot docs).

**Comment by chanhyeong** [comment]
@bclozel @garyrussell
> Can you share where those links are? Could you give us a URL?

I'm sorry for the unclear information. I reported about [`Apache Kafka Support` in spring-boot docs](https://docs.spring.io/spring-boot/docs/current/reference/html/messaging.html).
There is an one incorrect link now. (`See also features.html for more information.`).

I found where it is. (https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-docs/src/docs/asciidoc/messaging/kafka.adoc)
Can I close this issue? Because I think the last one is about spring-boot.

**Comment by garyrussell** [comment]
@chanhyeong Thanks; @bclozel I don't have permissions to close this; can you do so? Thanks.
