### ISSUE TITLE
Cannot click links on /docs when site goes responsive

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#107]
Repro:
1. Go to http://spring.io/docs
2. Reduce browser width until nav goes responsive
3. Click on "Spring Framework"
4. Attempt to click on any "Reference" or "API" link
5. Notice that the mouse cursor never changes into link-clicking mode
6. Notice that if one does click, the pop-up window simply disappears
7. Now stretch the window back out
8. Repeat steps 3 and 4
9. Notice that links work as expected.

**Comment by bclozel** [comment]
We've redesigned the website since, so I'm closing this issue as outdated.
