### ISSUE TITLE
"Spring Cloud Gateway Sample" and "Spring Cloud Samples Gateway"

### ISSUE THREAD

**Issue by donhuvy** [spring-io/sagan#1077]
URL https://spring.io/projects/spring-cloud-gateway#samples

![image](https://user-images.githubusercontent.com/1328316/205603929-3da4ff16-c3fc-49b7-97f4-279e01bc5b20.png)

Please naming more meaningful.

**Comment by sreenath-tm** [comment]
Hi, I would like to contribute to this issue. Can you please assign this issue to me and let me know what I am supposed to do?

**Comment by bclozel** [comment]
They're different URLs to different samples - the description under the link makes it clear.
