### ISSUE TITLE
spring-cloud-2022-0-2-is-available still uses '2022.0.1' release train in the Gradle script

### ISSUE THREAD

**Issue by DevDengChao** [spring-io/sagan#1082]
![image](https://user-images.githubusercontent.com/16363180/229000524-47576ad0-db2a-4a3b-8228-1009fef36af1.png)

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-io/start.spring.io/pull/1147

Note that this project has been retired and we will archive the repository soon.
