### ISSUE TITLE
page not found in docker guides

### ISSUE THREAD

**Issue by Aminmalek** [spring-io/sagan#1083]
![Screenshot from 2023-04-23 16-11-15](https://user-images.githubusercontent.com/76443257/233840456-045d0c1d-4de0-4e7b-956a-28060893f0cb.png)
in this doc when I clicked on Docker hyperlink the page https://spring.io/guides/gs/spring-boot-docker does not found.

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-guides/top-spring-boot-docker/issues/30
