### ISSUE TITLE
Set up CLA integration

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#121]
- [x] @nebhale to update re getting CLA integration online by March 24th / 25th (3/15)
- [x] @dussab to update re DB provider per https://github.com/spring-io/sagan/issues/121#issuecomment-34083418 (2/4)
- [x] @dussab to update with status / next steps, per https://github.com/spring-io/sagan/issues/121#issuecomment-33946083 (2/3)
- [ ] @dussab and @cbeams to discuss resourcing
- [ ] When this work is complete, update [CONTRIBUTING.md](https://github.com/spring-io/sagan/blob/master/CONTRIBUTING.md
) to reflect the new process.

----

@cbeams wrote to @nebhale:

> Brian told me a while back that you'd been working on an equivalent to CLAHub for us?

> I'd really like to be up and running against that when we open source Sagan. Should have thought to ask you about it last week.

> Let me know and we can set something up to discuss.

@nebhale responded:

> Defintely, let's do it.  I've had about zero input from anyone outside of me so I'm interested in having a second set of eyes looking at it.  It needs to be re-written as a boot application to stay on message, and isn't a fancy single-page app, but code is [here][1], and a running instance is [here][2].  At the moment, it only takes care of the signing side of the work-flow, and doesn't have GH integration yet (everything stopped for S1).  Ping me whenever you've got 30 minutes and we can chat about where to take it from here.

[1]: https://github.com/gopivotal/github-cla-integration
[2]: http://gopivotal-cla.cfapps.io

**Comment by rwinch** [comment]
I randomly ran into this and thought I would mention that I am currently working on a project for CLA. See https://github.com/rwinch/github-cla

**Comment by bclozel** [comment]
This issue is now longer relevant.
The CONTRIBUTING file will be updated once the new CLA application is up and running.
