### ISSUE TITLE
Replace font family with better rendering variants

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#129]
See original story at https://www.pivotaltracker.com/story/show/56568046 for complete background.

Bottom line, however, is that our current font families (Google fonts) do not render properly in Chrome on Windows, and generally do not render in-browser as well as we would have liked with in comparison to Photoshop.
- [ ] @dararith to choose new fonts as time permits
- [ ] @jacksoncvm to implement

**Comment by bclozel** [comment]
We've redesigned the website since, so I'm closing this issue as outdated.
