### ISSUE TITLE
Include date for spring.io blog posts in search results

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#134]
- [ ] ready to implement Dararith's design laid out in https://github.com/spring-io/sagan/issues/134#issuecomment-30268536
- [ ] make sure to sort results by publication date

---

As requested by @phumphrey on behalf of a user tweeting to @springcentral, it would be best if the date of a blog post shows up in its search results, e.g.

![screen shot 2013-11-11 at 2 23 52 pm](https://f.cloud.github.com/assets/301810/1512819/925e3274-4ad4-11e3-98ab-a5c9e52ec36e.png)

**Comment by bclozel** [comment]
We've removed the search feature temporarily from the website. We'll consider a completely new design in a future version.
