### ISSUE TITLE
500 response from missing guide

### ISSUE THREAD

**Issue by dsyer** [spring-io/sagan#171]
http://spring.io/guides/gs/not-a-guide should be a 404 I would say (but currently it's a 500).

**Comment by pintiliea** [comment]
It's a 404 response today.

![404](https://cloud.githubusercontent.com/assets/23454490/20544408/37cdd270-b10a-11e6-8490-a2abb8f890c2.jpg)

**Comment by pintiliea** [comment]
It's a 404 response now.

![404](https://cloud.githubusercontent.com/assets/23454490/20544466/8a49c270-b10a-11e6-9134-e9d121526526.jpg)

**Comment by bclozel** [comment]
Thanks for the heads up! I'm closing this issue then.
