### ISSUE TITLE
add links to md5 and sha checksums to STS/GGTS download page

### ISSUE THREAD

**Issue by martinlippert** [spring-io/sagan#174]
I know, we left those links out when doing the first release, but people are asking for it. So it would be great if we could find a way to get the links to md5 and sha checksums back on the STS/GGTS download page.

I think the best place would be a very small link in the download context menu (the one that appears when you click on "Based on Eclipse 4.3.1", for example). At the moment it gives you four options. Each of those options should get an md5 and a sha checksum download link right below the "dmg 379MB" entry (for example).

**Comment by bclozel** [comment]
This page has been removed from the website. I'm closing this issue as outdated.
