### ISSUE TITLE
Prevent reference and api doc links from being presented if value set to NONE

### ISSUE THREAD

**Issue by olivergierke** [spring-io/sagan#175]
In [`project-metadata.yml`](https://github.com/spring-io/sagan/blob/master/sagan-common/src/main/resources/project-metadata.yml#L72) we sometimes configure the links for the JavaDoc and reference documentation to `NONE`.

This still causes the links to be rendered but effectively leading back to the project site, which users consider "broken" (see [this tweet](https://twitter.com/bytor99999/status/407656193507614720) for example).

Any chance we can remove the rendering of these links?

**Comment by olivergierke** [comment]
This came up in a discussion with @markpollack again.

**Comment by olivergierke** [comment]
I'd like to raise the priority of this one as it just comes up over and over again. :(

**Comment by gregturn** [comment]
Turns out, the issue at hand is here => https://github.com/spring-projects/gh-pages/blob/gh-pages/_includes/widget_templates.html#L20-L23

A patch shouldn't be too difficult for me to muster up.

**Comment by gregturn** [comment]
In fact, there appears to be an open issue on the same subject in the right repo => https://github.com/spring-projects/gh-pages/issues/6

**Comment by bclozel** [comment]
Fixed by spring-projects/gh-pages#12 - an [update to your project's gh-pages branch](https://github.com/spring-projects/gh-pages#how-to-keep-common-gh-pages-content-up-to-date) is required.
