### ISSUE TITLE
Clarify unlisted Spring Projects

### ISSUE THREAD

**Issue by kennyk65** [spring-io/sagan#183]
There are a number of Spring related projects in the wild that are not listed in the Spring Projects page of Spring IO.  Examples include Spring .net, Spring dynamic modules, Spring Python.  

These absences can cause some confusion to those researching these technologies. (I know I'm confused!)  A curious researcher will be quickly puzzled to discover a spring framework.net domain that is not mentioned at all on spring.io.  It sends the subliminal message that there is something unsupported / uncoordinated about this project and that it should be avoided.

It might be nice to publish some clarity about this.  Suggest a 'other projects' page where we can list the current state of these other projects, who runs them, why they are not listed in the main page, etc.

**Comment by bclozel** [comment]
We didn't get much demand for this and we've redesigned the website since.
I'm closing this issue as a result.
