### ISSUE TITLE
Add Marketo javascript tracking code for select pages on Spring.io

### ISSUE THREAD

**Issue by asargent** [spring-io/sagan#198]
Add Marketo javascript tracking code for select pages on Spring.io, specifically pages that signal "commercial intent", i.e., a desire to purchase support, training or consulting. 

This will let us better score leads, to provide a prioritized list of leads to our sales team to follow up on. For instance, Marketo Javascript can tell us if an individual has signed up for a webinar, visited  Spring AMQP doc pages on Spring.io, and has looked at RabbitMQ pages on GoPivotal.com. All those activities contribute to a user's lead score.

Lead scoring is critical. We've had reps get over 200 leads and they simply don't know which ones to start with.

Deliverables are basically putting Marketo Javascript on perhaps 100 pages on Spring.io. 

Contact Pieter Humphrey and/or Al Sargent when it's time to implement this.

**Comment by bclozel** [comment]
I believe that the marketo script has been in production for a while now.
Closing this.
