### ISSUE TITLE
Add ability to "tag" blog posts to make it easier to tie in with existing guides

### ISSUE THREAD

**Issue by gregturn** [spring-io/sagan#235]

**Comment by ossdhaval** [comment]
Hi,

I would like to make an attempt at this. Is this still up for contribution?

Regards.

**Comment by bclozel** [comment]
Thanks for the offer @ossdhaval , but the site evolved quite a bit since we created this issue and I think we'll close this in favor of #992. We still need to gather requirements and work on mockups before working on that other issue.
