### ISSUE TITLE
Tweak the way the blog table headers are styled

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#240]
- [ ] @dararith to weigh in on https://github.com/spring-io/sagan/issues/240#issuecomment-33210153

---

On Jan 22, 2014, at 8:45 PM, @rwinch wrote:

> @cbeams @gregturn @briancavalier Thanks for the fast turnaround [on #233]. This is likely my own fault due to waiting till the change was out, but I'm wondering if we might make a few tweaks to the way the headers are styled. These are obvious preference, so please feel to let me know if you disagree with them.
> - I don't see a border around the header cells so this looks detached from the rest of the table. Is this intentional or possibly due to my markdown? Could we consider adding the border around the header cells?
> - It might be nice to bold and perhaps center the header columns. The centering may look a little weird due to the 100% width
>   These suggestions are similar to the way GitHub styles it here https://github.com/rwinch/encryption-not-signing#review-of-xor
> 
> Thoughts?

**Comment by bclozel** [comment]
We've redesigned the website since, so this issue is now outdated.
