### ISSUE TITLE
Automated scanning all guides after a deploy

### ISSUE THREAD

**Issue by gregturn** [spring-io/sagan#246]
In order to warm up the caches / to avoid users having to incur the wait time of downloading and processing Asciidoc, etc.

Challenges include doing this across all instances of the app (each instance maintains its own cache at present). May want to wait on this issue until we have a final arrangement for cache population / sharing there. For example, it could end up that we store this information in elasticsearch, at which point it would be shared and only need to be populated once.

**Comment by bclozel** [comment]
This can be considered as deprecated, since #467 will automatically update guides in a shared cache.
