### ISSUE TITLE
Remove SpringBoot whitelabel error page

### ISSUE THREAD

**Issue by paulc4** [spring-io/sagan#288]
Issue #287 pertains to a bad link: www.springsource.org/insight which generates the following output in Times Roman text:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Fri Feb 28 04:33:26 UTC 2014
There was an unexpected error (type=Not Found, status=404).

I believe this is the default Spring Boot error page, but is not a good look.  A bad link at spring.io generates a much 'nicer' 404 page - try for example http://spring.io/xxx.

**Comment by wramirez2401** [comment]
Hello, also I have the same problem as solved?

**Comment by bclozel** [comment]
I think this issue should be closed, as http://spring.io/xxx is now mapping to a custom error page:

![image](https://cloud.githubusercontent.com/assets/103264/17863544/4a77899c-689a-11e6-8b85-08c401bc2c45.png)

@wramirez2401 which URL is showing a whitelabel error page?
