### ISSUE TITLE
Support importing sources and running site directly from VCS/build.gradle into IDEA

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#320]
The import from VCS part works fine, but there are issues when importing from build.gradle as opposed to generating IDEA metadata with `./gradlew idea`.

Without this, users are forced to work at the command-line level. Not a problem for some, but a 100% in-IDE experience would be great.

Some of the issues look specific to IDEAs Gradle integration and terminal implementation:
 - [ ] reproduce these errors and create YouTrack issues for each.

**Comment by bclozel** [comment]
Latest IDEA versions work fine fine, no command-line involved nor IDEA files generation.
