### ISSUE TITLE
Un-@Ignore BasicAcceptanceTests

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#332]
@Ignore was added at the class level in a0381182e53e80610e50fab25a1c4fa5dd251ee7 in order to avoid build failures on Travis such as this one: https://travis-ci.org/spring-io/sagan/builds/21877994

```
:sagan-site:integTest

saganx.BasicAcceptanceTests > classMethod FAILED

java.util.concurrent.TimeoutException at BasicAcceptanceTests.java:50

169 tests completed, 1 failed, 1 skipped

:sagan-site:integTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':sagan-site:integTest'.

```

At a glance, it looks like this may be related to the use of `FreePortFinder` in those tests.

**Comment by bclozel** [comment]
We've reworked the codebase since - I'm closing this issue as outdated.
