### ISSUE TITLE
Research Travis CI HipChat notifications (vs. plain messages)

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#333]
The Travis CI build (see #331) sends messages to the Sagan HipChat room on the completion of every build (whether failed or successful). This is good, but ideally, it would 'notify' when there is a failure, such that the dock icon bounces, etc.

The Travis documentation points out that [`use_notice: true` can be specified for IRC notifications](http://docs.travis-ci.com/user/notifications/#IRC-notification), but mentions no equivalent property for HipChat.

**Comment by bclozel** [comment]
This channel moved to Slack
