### ISSUE TITLE
Blog Serves Up Empty Page Instead of 404 with Bad URL

### ISSUE THREAD

**Issue by garyrussell** [spring-io/sagan#341]
https://spring.io/blog/2014/04/01/spring-boot-1-0-ga-release

Vs

https://spring.io/blog/2014/04/01/spring-boot-1-0-ga-released

**Comment by tmrd993** [comment]
Seems like this is fixed?

**Comment by bclozel** [comment]
Yes this is fixed. Thanks for commenting!
