### ISSUE TITLE
Icons render poorly on retina display

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#386]
See attached.

![screen shot 2014-05-13 at 11 53 32 am](https://cloud.githubusercontent.com/assets/301810/2955732/8313755a-da84-11e3-8de5-b350ef654015.png)
![screen shot 2014-05-13 at 11 53 40 am](https://cloud.githubusercontent.com/assets/301810/2955741/9bca03c0-da84-11e3-97b9-04cbf9ccbbf8.png)

**Comment by cbeams** [comment]
Ping!

**Comment by bclozel** [comment]
We've redesigned the website and I can't reproduce this issue now. Thanks!
