### ISSUE TITLE
Searching Spring.io for documentation returns with non-useful documentation.

### ISSUE THREAD

**Issue by berlin-ab** [spring-io/sagan#387]
It returns with snapshot versions or old versions.  I expect to see the latest version's documentation at the top and an obvious way to choose which version for when I'm using an older version.

![screen shot 2014-05-13 at 10 57 44 am](https://cloud.githubusercontent.com/assets/87432/2959033/fb199064-daae-11e3-97c3-402d64d27381.png)

**Comment by bclozel** [comment]
Fixed with #546
