### ISSUE TITLE
harcoded navigation on layout template

### ISSUE THREAD

**Issue by gigfork** [spring-io/sagan#391]
Currently Navigation is hardcoded in:

https://github.com/spring-io/sagan/blob/master/sagan-site/src/main/resources/templates/layout.html

Would be nice to support at least Authenticated and Non-Authenticated requests and have the uih to be able to retrieve that "List" and iterate over it and automatically generate that html content.

**Comment by bclozel** [comment]
We've redesigned the website and I can't reproduce this issue now. Thanks!
