### ISSUE TITLE
Fix typos in templates creating 404 links

### ISSUE THREAD

**Issue by bclozel** [spring-io/sagan#393]
Possible typos:
- [ ] `http://spring.io/team/mpollack/'https://twitter.com/springcentral` - links to springcentral twitter account in the team page
- [ ] `http://spring.io/blog/2012/03/12http://www.youtube.com/springsourcedev-creating-spring-insight-plugins` - links to youtube videos in blog posts
- [ ] `http://spring.io/blog/2008/12/11/.atom` - links to ATOM feeds in blog posts

**Comment by simrin051** [comment]
@bclozel 
Can i take up this issue.

**Comment by bclozel** [comment]
I think those typos have been fixed when we updated the design.
I'm closing this issue. Thanks!
