### ISSUE TITLE
Question - build as WAR

### ISSUE THREAD

**Issue by dchartfield** [spring-io/sagan#419]
I noticed that there is an issue with running the jar ( https://github.com/spring-io/sagan/pull/191 ), and I was wondering if a WAR could be build and run in say Tomcat on an EC2 instance? 

I see that the gradle spring boot plugin can build the WAR by adding this:
```
apply plugin: 'war'
war {
    baseName = '$BASENAME'
    version =  '$VERSION'
}
```
and removing the embedded tomcats. But applying this to the sagan-site project the static resources from sagan-client aren't included. Is the Sagan project setup to build a WAR?

**Comment by bclozel** [comment]
Building the war following [Boot's instructions](https://spring.io/guides/gs/convert-jar-to-war/) and running the application with the production profile should work. We're trying to load resources from the filesystem in dev mode only.
