### ISSUE TITLE
Document how to remote debug sagan app

### ISSUE THREAD

**Issue by ttddyy** [spring-io/sagan#422]
It took me a while to figure out this command to remote debug sagan app.
`./gradlew :sagan-site:run --debug-jvm`

Or add `"-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"` to `applicationDefaultJvmArgs` in `build.gradle`

----

These are the ones didn’t work. (breakpoints are skipped) :<
- `GRADLE_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005” ./gradlew :sagan-site:run`
- `JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005” ./gradlew :sagan-site:run`
- Starting `SiteMain` from IDE works for dynamic(java) part, but doesn’t serve static contents

It would be nice to be documented this kind of information probably on developer section in wiki.

Thanks,

**Comment by bclozel** [comment]
Done.
See https://github.com/spring-io/sagan/wiki, right menu.
