### ISSUE TITLE
Improve search results

### ISSUE THREAD

**Issue by olivergierke** [spring-io/sagan#449]
I've just tried to find a blog post of mine in our blogs. I entered "Spring Data REST projection" into our website's search window, filtered by blog and get this [0]. The first few result pages only show blogs from almost two years ago (actually, it would be helpful to see the release date in the search results, but I already found a long stale #134 for that).

I would have expected that a relatively [recent match](https://spring.io/blog/2014/05/21/what-s-new-in-spring-data-dijkstra) would should pretty high in the result list. Do we need to weigh the release date of a post stronger?

**Comment by olivergierke** [comment]
I'd like to raise the importance of that one. No matter what I search for, the search never returns any useful results: Just try [this search](https://spring.io/search?q=Oliver+Gierke+projection&filters=Blog%2FEngineering) and see what results you get:

![bildschirmfoto 2015-02-21 um 20 17 37](https://cloud.githubusercontent.com/assets/128577/6315592/bc1ec9a0-ba06-11e4-8533-995154cfa1e8.PNG)

[This post](https://spring.io/blog/2014/05/21/what-s-new-in-spring-data-dijkstra) should clearly be a strong match as it contains the terms searched for whereas the above result only contains related phrases but never the phrase searched for itself.

Also, the results should definitely carry their publication dates, as this would at least make obvious that the ones found for my search above are pretty dated.

**Comment by bclozel** [comment]
Hi @olivergierke and @paulc4
I've addressed many issues in #546 - but all search issues are not fixed. For example, that very same search query still does not return the blog post entry you expect.

But the marketplace service we're using now provides some analytics features; we'll know about the most popular search queries and we'll optimize the search engine for them.

For example:

* the search engine now supports fuzziness; but we can tweak that parameter to the distance we want
* the scoring process favors matches in titles and API/reference docs marked as "current version"
* etc, etc

I'm closing this issue right now - I'll get a couple of weeks worth of analytics and start digging. I'll let you know!

Thanks for this report.
