### ISSUE TITLE
simplify tools download page

### ISSUE THREAD

**Issue by martinlippert** [spring-io/sagan#461]
We should simplify the tools download page (https://spring.io/tools/sts/all + https://spring.io/tools/ggts/all). Since we now provide only the 32bit + 64bit ZIP files for each platform, we don't need the popup that shows all the various download links anymore. Instead we should show the download items directly in the download box of each supported platform. This makes them directly available on that page without the need to dive into a popup anymore.

**Comment by bclozel** [comment]
The new tools page is superseding the former ones. Closing this issue.
