### ISSUE TITLE
New and Noteworthy: Missing Logo in Header

### ISSUE THREAD

**Issue by dararith** [spring-io/sagan#462]
http://docs.spring.io/sts/nan/v361/NewAndNoteworthy.html

Most likely mis-positioned of sprite.

-dararith

**Comment by bclozel** [comment]
Hey @martinlippert , is it something on your side?

**Comment by martinlippert** [comment]
Yepp, this was a missing png file on my side. This is fixed now.

**Comment by martinlippert** [comment]
And thanks for pointing me to this!!!

**Comment by bclozel** [comment]
Thanks!
