### ISSUE TITLE
Fix GSG CSS so that clicking inside the build section does NOT collapse it

### ISSUE THREAD

**Issue by gregturn** [spring-io/sagan#476]
The headers for each build section have JavaScript to expand/collapse that section along with a "hand" icon from the CSS. Need to alter the CSS so that the "hand" is only shown on the header, and that the JavaScript event handler only expands/collapses when clicking on that part.

/cc @unscriptable @briancavalier

**Comment by r-murphy** [comment]
+1. This breaks copy/paste from samples.
