### ISSUE TITLE
Compilation/build issue

### ISSUE THREAD

**Issue by agingade** [spring-io/sagan#489]
trunk> ./gradlew :sagan-site:bootRun

FAILURE: Build failed with an exception.
- Where:
  Build file '/export/shared_build/users/anil/sagan/trunk/build.gradle' line: 90
- What went wrong:
  A problem occurred evaluating root project 'sagan'.
  
  > Could not generate a proxy class for class org.springframework.boot.gradle.SpringBootPluginExtension.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.965 secs

**Comment by eyaleee** [comment]
hey there, I have the same problem. my JAVA_HOME is set correctly to the JDK 1.8.0_25, and I can see that the right java.exe file is called. still facing the same issue with the spring jar...

by the way I'm working with a flatdir repository, with the spring jar in place. I also know that the folder access is correct cause once I change the folder name the build fails with a whole lot of missing jar files.

**Comment by bclozel** [comment]
Hi @eyaleee 

What command are you using? `./gradlew :sagan-site:bootRun` or are you trying to run the executable jar `java -jar target/sagan-site.jar`?

Could you give some information on your:
* operating system
* output of `./gradlew --version`
* the complete stacktrace of that command with --info

**Comment by thienan93** [comment]
Hi all, I also faced the same issue. JAVA_HOME is JDK 1.8. There are some information:
```
apply plugin: 'spring-boot'

dependencies {
    runtime fileTree(dir: 'lib', include: '*.jar')
}

buildscript {
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.3.3.RELEASE'
    }
    repositories {
        flatDir {
            dirs 'build-lib'
        }
    }
}
```

**Comment by bclozel** [comment]
If `./gradlew --version` also gives you a JDK < 1.8, then you should look into your OS setup and turn to gradle forums or StackOverflow to resolve this issue.
