### ISSUE TITLE
Documentation for sagan

### ISSUE THREAD

**Issue by khat33b** [spring-io/sagan#496]
Could you release the software documents for sagan (SRS, Design Documents etc.) so it would be easier to understand the working of the site?

**Comment by bclozel** [comment]
Hi,

This project started out with minimal documentation - most of it was actually within stories in a [Pivotal Tracker project](http://www.pivotaltracker.com/).

This project evolves now constantly with continuous delivery. As for documentation, you'll find:
* features by browsing http://spring.io
* howtos on the [wiki](https://github.com/spring-io/sagan/wiki)
* comments about the design and code in code comments by browsing this repository (far from complete)

Don't hesitate to open issues and ask questions, we've got a label for that!
