### ISSUE TITLE
Thymeleaf configuration

### ISSUE THREAD

**Issue by khat33b** [spring-io/sagan#500]
Where is the thymeleaf configuration done in sagan? How does it know to search in 'src/main/resources' for the templates?

**Comment by bclozel** [comment]
It's a Spring Boot feature (that can be customized within `application.yml`) - see [Spring Boot reference doc](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-template-engines).
