### ISSUE TITLE
Support topical guides

### ISSUE THREAD

**Issue by bclozel** [spring-io/sagan#504]
Add a new /docs/topics page for topical guides.

A lot of code should be shared between this and understanding guides, getting started guides.

All topical guides live under a separate repository: spring-guides/topical-guides

**Comment by bclozel** [comment]
See https://github.com/dsyer/spring-security-architecture by @dsyer

**Comment by dsyer** [comment]
Also some of these: http://pivotal-guides.cfapps.io/frameworks/spring/ (I particularly like the "testing" one). The authors have said we can take as much content as we want. Hopefully they would help maintain it if it was in a public repo too (it isn't at the moment).
