### ISSUE TITLE
Asciidoc guides not rendering variables properly

### ISSUE THREAD

**Issue by bclozel** [spring-io/sagan#507]
See spring-guides/gs-uploading-files#13

**Comment by gregturn** [comment]
Resolved by https://github.com/spring-guides/getting-started-macros/commit/d4a06761e7a3ed00558e56733be0d7fb43ddf5a1

**Comment by bclozel** [comment]
For the record, #488 updated Asciidoctor - and that particular syntax may not be supported anymore.
