### ISSUE TITLE
Make sure project pages produce reasonable HTML with JavaScript disabled

### ISSUE THREAD

**Issue by olivergierke** [spring-io/sagan#508]
if you disable JavaScript for your browser, very core aspects of the individual project pages are gone:
- the list of currently available and maintained version plus the links to the APIs and reference documentation
- the download box solely consists of a hint to use Maven or Gradle. No coordinates listed.

![bildschirmfoto 2015-03-17 um 11 25 19](https://cloud.githubusercontent.com/assets/128577/6685259/67d46dd8-cc98-11e4-8fef-c4e57c048b1c.PNG)

Seems we're basically violating [client principle 4](http://roca-style.org/#unobtrusive-javascript) here. Especially as Sagan is considered a reference web application we should be good citizens when it comes to principles of the web.

**Comment by bclozel** [comment]
Those pages aren't hosted on Sagan but on github.io - JavaScript is required here to fetch metadata information from Sagan. I'd be happy to help improve the current situation.

A whole different strategy can be suggested in a new issue in spring-projects/gh-pages .
In my opinion, we've only got two choices for this:
* stick with the current mix of static content and a backbone application (breaking that principle)
* go with a full-static setup and commit changes every time you change the version information in a project page (see https://spring.io/admin/projects/spring-hateoas ).

**Comment by gregturn** [comment]
Rebuilding pages everyone an update is done will push the pages to he even more out of date. 

I have an idea that might be best of both worlds. Can we make the project info publicly visible on sagan? (Perhaps it already is?). In the comments or stuff that is only visible when JS is disabled can show a link to where the source comes from.

That way, the 99% that use JS require no more management and the other 1% have a trail to the source of information with no extra effort on our end.

**Comment by bclozel** [comment]
The new project page layout is fixing this - project pages are now rendered on the server.
