### ISSUE TITLE
remove grails guides from spring.io/guides

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#513]
remove, perhaps archive content in case G or G want it?

https://spring.io/guides/gs/accessing-data-gorm-mongodb/
https://spring.io/guides/gs/accessing-data-gorm/

**Comment by bclozel** [comment]
Hey @gregturn - could you rename both [gs-accessing-data-gorm-mongodb](https://github.com/spring-guides/gs-accessing-data-gorm-mongodb/) and [gs-accessing-data-gorm](https://github.com/spring-guides/gs-accessing-data-gorm/) and add a "deprecate-" prefix to those repos?

Even if March 1st is the official date, those guides are having issues with their sidebar content and are showing HTTP 500 errors on spring.io right now.

**Comment by gregturn** [comment]
Done. Might take a few minutes for the caches to clear.

**Comment by bclozel** [comment]
Awesome, thanks Greg!
