### ISSUE TITLE
update https://spring.io/projects to remove groovy

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#514]
remove groovy from https://spring.io/projects

**Comment by ashokgudise** [comment]
Hi I am curious to know the reason, why it has been removed under spring projects. Is it because Groovy is becoming part of apache projects? Pls advice.


Regards
Ashok Gudise

**Comment by bclozel** [comment]
[Pivotal is not sponsoring Groovy anymore](http://blog.pivotal.io/pivotal/news-2/groovy-2-4-and-grails-3-0-to-be-last-major-releases-under-pivotal-sponsorship), so it makes sense to remove it from that list.

But the Spring team is still actively supporting the use of groovy in our projects, so the Groovy language is [still part of the Spring IO Platform](https://spring.io/platform).
