### ISSUE TITLE
Scroll to closer to the current element when user reveals or hides gradle/maven

### ISSUE THREAD

**Issue by dsyer** [spring-io/sagan#522]
In https://github.com/spring-io/sagan/blob/master/sagan-client/src/feature/hide-show-guide/main.js we scroll to a fixed location when the user hides or reveals maven/gradle content. That's great when there is only one element doing this on the page, but when there are complex instructions in the guide relating to Maven or Gradle you need to be able to scroll to the current location, not the top of the page.

**Comment by bclozel** [comment]
We've removed gradle/maven code snippets since from guides.
