### ISSUE TITLE
Implement sagan with micro-services and Spring Cloud

### ISSUE THREAD

**Issue by dima767** [spring-io/sagan#534]
Not urgent, but would be real nice for a reference implementation of somewhat complex micro-services based app with all the bells and whistles of Spring Cloud e.g. Eurika, Hystrix and co.

**Comment by bclozel** [comment]
Hi @dima767 
Right now Sagan is "made of" 2 services: the site application (the website itself) and the indexer (indexes documentation, blog posts, etc - into our ElasticSearch index); I haven't felt the need to decouple more/cut Sagan into smaller pieces.

I'm definitely considering using some pieces of Spring Cloud; for example, Hystrix could definitely help with calls to remote web services such as our search index, github or stackoverflow.

Did you have something special in mind?

**Comment by dima767** [comment]
Thanks for the reply. Nothing special in mind, just feel the need for the real world example/reference implementation of all the Spring Cloud and micro services stuff. The "buzz" around it is great, but all the smallish examples and guides just don't cut it. Need a real world, somewhat complex reference app.

Best,
D.

**Comment by dima767** [comment]
Well, I guess this issue could be closed.
