### ISSUE TITLE
Typo in Spring cloud config site

### ISSUE THREAD

**Issue by shahid21st** [spring-io/sagan#535]
I opened this issue - https://github.com/spring-cloud/spring-cloud-config/issues/125 to fix it and which is fixed already, but its still showing the wrong spelling in http://cloud.spring.io/spring-cloud-config/ - I thought Sagan will somehow pull the info from the github project readme. But it didn't happened.

**Comment by dsyer** [comment]
You reported a problem in the README not the home page. Maybe open a new issue with Spring Cloud?
