### ISSUE TITLE
use System.js and jspm

### ISSUE THREAD

**Issue by bclozel** [spring-io/sagan#541]
Right now the client application is relying on the curl loader and the cram build tool.
For many reasons, now is the time to move this to a different arrangement, with System.js and jspm.

- [x] add jspm as an npm developement dependency
- [x] add all bower dependencies as jspm dependencies; use the npm registry for all dependencies, since you can [run pretty quickly into rate limiting](https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#github-authentication-environment-variable) (especially on CI).
- [x] remove bower and all its dependencies
- [x] remove npm-shrinkwrap ?
- [x] remove cram altogether and replace it with the gulp-jspm plugin
- [x] update the build.gradle file if necessary for packaging optimized resources
- [x] rewrite `run.js` to use System.js instead of curl. All modules are commonJS, so maybe no work is necessary
- [x] update `layout.html` with all changes
- [x] make sure that everything works properly in dev mode, including the `/team` page which loads modules at runtime
- [x] fix #586 as this library is not loading properly right now
- [x] build a separate "map" module containing : `map feature + the gmaps lib - jquery`
- [x] check that the gulp build has produced a proper webjar that works when running locally the application with `java -jar sagan-site.jar`
- [x] deploy to staging and make sure that everything works fine and that front-end performance is still OK

**Comment by bclozel** [comment]
See https://github.com/bclozel/spring-resource-handling/commit/7dc7b08efb3b63c37ecd037b738c93b6ebb429da and https://github.com/bclozel/spring-resource-handling/commit/de2743983d62d9483326f1bfeb1db8aab226d062

**Comment by jadekler** [comment]
Note on #2: not all deps live in the npm registry that I can see. The offenders are:

```
"bootstrap": "github:twbs/bootstrap@^2.3.2",
"curl": "github:cujojs/curl@^0.8.12",
"google-code-prettify": "github:google/code-prettify@master",
"jquery-timeago": "github:rmm5t/jquery-timeago@^1.4.1",
```

Bootstrap could be upgraded to 3.0 to fix the problem, but they don't have any 2.x versions on npm:

```
$ npm view bootstrap versions

[ '0.0.1',
  '0.0.2',
  '3.1.1',
  '3.2.0',
  '3.3.0',
  '3.3.1',
  '3.3.2',
  '3.3.4',
  '3.3.5' ]
```

**Comment by bclozel** [comment]
Just updated the description and forced-push the `jspm` branch. There are still some outstanding items to deal with.

**Comment by jadekler** [comment]
:+1: will take a look tonight @bclozel. Figured there'd be some loose ends heh
