### ISSUE TITLE
Idiot-proofing the documentation links on the Quick Start project pages

### ISSUE THREAD

**Issue by hangtwenty** [spring-io/sagan#568]
Followup from https://github.com/spring-cloud/spring-cloud-netflix/issues/388.

I've been going about several Spring projects for a few weeks now, never realizing where the link to the more-in-depth documentation is. This is a UI issue on the Quick Start page designs.

Here's what happened in my pea brain...

![How I misunderstood the layout on a Spring Project page](http://s28.postimg.org/d2popdgod/Screen_Shot_2015_06_29_at_10_51_25_AM.png)

As a result, I was all around different blog posts, StackOverflow, etc., thinking that Spring did a poor job of documenting these little side projects. Where were the real docs?

I know it might seem stupid! But! But I think this is how we improve the UX for an outsider "like me" — be honest about how you were confused by something like this ... and try to make it less confusing for others.

More generally, the issue is that [many](http://www.dropwizard.io/) [other](http://flask.pocoo.org/docs/0.10/quickstart/) [getting](http://docs.python-requests.org/en/latest/user/quickstart/) [started](https://www.djangoproject.com/start/) pages make it abundantly clear what documentation you should go to next. Maybe it's obvious _to Spring or Java developers_ that "Reference" would actually be helpful in this way, but to someone from the outside (Python in my case), "Reference" doesn't sound like the helpful documentation you're looking for. I thought it was Javadocs or something autogenerated, and I didn't think much about what API meant ... And anyway, in the case of Spring Cloud, "API" turns out to link you to the GitHub page. So it's not like you'd click "API" and then deduce that "Reference" is actually the prose docs you're looking for.

Also, these links are out of sight by the time you're at the bottom of the Quick Start page.

Some things that could help:
- At bottom of each Quickstart guide, provide link to "Reference" because that's what's really helpful, if you're trying to go beyond the "Quickstart" content (and you've scrolled to the bottom of the Quickstart page).
- Update existing link: Emphasize the "Reference" link, for the latest release. (Bold?)
- Or make "Spring Cloud Documentation" header a link, probably make it bold. This link ought to go to the "Reference" docs for latest release. (This would be the "obvious" choice for a user like me.)

Whatever choice is used, the same would go for "Spring <Project> Documentation" on other pages ...

Thank you for bearing with me. Hopefully we can make this a bit more welcoming.

**Comment by hangtwenty** [comment]
Here's another idea for something that could help ... maybe the best one:

* Next to the *Quick Start* button, add an equal-sized *Current Documentation* button that links you to the current docs. (Reference Guide for current version.)

This would be dead-simple for newcomers! And not confusing for people looking for "more information" like javadocs etc. (they will look for other smaller links.)

**Comment by bclozel** [comment]
We've completely redesigned the website and provided new "Why Spring" and "Quickstart" pages. Hopefully these new pages address the concerns listed in this issue. At least the changes are important enough to make this issue outdated. Thanks!
