### ISSUE TITLE
Guides: Category data isn't appearing in the list of guides

### ISSUE THREAD

**Issue by gregturn** [spring-io/sagan#574]
If you look at http://spring.io/guides and view the HTML, you'll notice that every guide has a [] listed. This is supposed to contain the categories for each guide to serve the filter. This data appears to be empty for every guide.

**Comment by bclozel** [comment]
I've found a bug.
The `tagMultimap` attribute (in the `GettingStartedGuides` repository) should not be implemented as shared state, as its values are only populated for a given guide if this very guide has been loaded with the `find` method.

The list of guides metadata should be properly computed and cached.

**Comment by bclozel** [comment]
A possible fix is to remove the projects metadata information from the document itself and move that to the repository description, much like we're doing right now with `Guide title :: Guide subtitle`. Turning that into `Guide title :: Guide subtitle :: spring-boot,spring-framework` should work. The trick is to move that information some place where we can get it from the repository API: https://api.github.com/orgs/spring-guides/repos
