### ISSUE TITLE
Windows gradlew.bat Build Fails With Exception

### ISSUE THREAD

**Issue by jmielkeway** [spring-io/sagan#587]
I get the following exception when trying to build the sagan project from the root directory with gradlew.bat (or gradlew.bat build):

FAILURE: Build failed with an exception.

*What went wrong:
A problem occurred configuring root project 'sagan'.
> Could not resolve all dependencies for configuration ':classpath'.
> Could not download dependency-management-plugin.jar (io.spring.gradle:dependency-management-plugin:0.5.3.RELEASE)
> Could not get resource 'http//repo.spring.io/libs_release/io/spring/gradle/dependency-management-plugin/0.5.3.RELEASE/dependency-management-plugin-0.5.3.RELEASE.jar'
> Could not GET 'http//repo.spring.io/libs_release/io/spring/gradle/dependency-management-plugin/0.5.3.RELEASE/dependency-management-plugin-0.5.3.RELEASE.jar'
> This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server

What steps can I take to seek a resolution?

**Comment by bclozel** [comment]
Strange.

Does this URL work in your browser?
http://repo.spring.io/libs-release/io/spring/gradle/dependency-management-plugin/0.5.3.RELEASE/

We [had issues with our repository a few hours ago](https://twitter.com/springops/status/649005970752991236) - did this just happen?

**Comment by jmielkeway** [comment]
Yes, this is recent, today, and yes, I can access that site now. Now my build has moved passed that point successfully, but fails on another dependency, but it *HAS* moved on from the one mentioned here. I will just keep trying to rebuild periodically. Thank you very much for your help!

**Comment by bclozel** [comment]
In case our artifact repository is the culprit, you can change the value [here](https://github.com/spring-io/sagan/blob/master/build.gradle#L9) with `'http://repo1.maven.org/maven2/'`.

If there are still issues, then your network connection (or Internet itself!) may be the one to blame...

**Comment by jmielkeway** [comment]
Well, now I've gotten about 60% of the way through the build - progress! But now I'm getting tripped up by some failed tests - 6 of the DocsWebhookController tests fail
![testfail](https://cloud.githubusercontent.com/assets/5845259/10206695/c94edad6-678d-11e5-9a4d-f18bc02e788e.png)

**Comment by bclozel** [comment]
Could you give more details about the failures?
Those tests should work, the app is [continuously built on travis](https://travis-ci.org/spring-io/sagan)

**Comment by jmielkeway** [comment]
Here is an image of the tests run with JUnit in STS. All  failures are unexpected exceptions of type sagan.guides.support.WebhookAuthenticationException, and thrown by the DocsWebhookController.verifyHmacSignature method. All error messages follow the pattern "Could not 
![stsimage](https://cloud.githubusercontent.com/assets/5845259/10232608/4b9ce0a2-684f-11e5-9781-9882a433fc93.png)
verify signature: 'actual', expected 'expected'"

**Comment by bclozel** [comment]
duplicates #619

**Comment by Sudip7** [comment]
@bclozel : could you please summarize what exactly needs to be done, Do I need to run my build using travis tool and I could run them locally.
