### ISSUE TITLE
OAuth tutorial

### ISSUE THREAD

**Issue by mohdalihpk** [spring-io/sagan#590]
OAuth is very popular, there is good support of OAuth in spring framework but unfortunately there are not enough tutorials. Please provide some OAuth basic tutorial step by step.

**Comment by bclozel** [comment]
We already have a quite [comprehensive guide on OAuth2](https://spring.io/guides/tutorials/spring-security-and-angular-js/). If this is not what you're looking for, you can [open a new issue on te guides repo and elaborate about this new guide idea there](https://github.com/spring-guides/getting-started-guides/issues).

Thanks!
