### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by jadekler** [spring-io/sagan#602]
Download link at http://cloud.spring.io/spring-cloud-config/ seems to be borked (assuming it's supposed to be a download link?) - clicking does nothing

**Comment by gregturn** [comment]
What download link?

**Comment by bclozel** [comment]
If we're talking about this, this is not a download link but rather a "download section" explaining how to get the maven/gradle artifacts.

![image](https://cloud.githubusercontent.com/assets/103264/11306477/51265050-8fb2-11e5-8744-88f00f7aa13a.png)

**Comment by gregturn** [comment]
That isn't a clickable button. The box instead contains the bits needed to plug into your build file, whether that's Maven or Gradle (see links to corresponding guides).

**Comment by jadekler** [comment]
Aha, apologies and thanks.
