### ISSUE TITLE
All guides are "Getting Started"

### ISSUE THREAD

**Issue by dsyer** [spring-io/sagan#603]
It's hard coded in the guide.html template. Could be extracted into the `AbstractGuide` as a property of the subclasses ("Getting Started" for gs guides and "Tutorial" for tut guides).

**Comment by dsyer** [comment]
Look good. But note that the `<title/>` is still "Getting Started".

**Comment by bclozel** [comment]
Ha, forgot to do that. Just pushed this - should be live in a few minutes.
