### ISSUE TITLE
Secret preview blog URLs

### ISSUE THREAD

**Issue by philwebb** [spring-io/sagan#609]
When writing a blog there is no easy way to share with a select group it before it is published. We could offer "secret" URLs (like secret Gists) so that we can send out a preview before publication.

**Comment by dsyer** [comment]
How would that work exactly? I'm not a huge fan of security by obscurity. I reckon it would bite us in the a*** eventually.

**Comment by philwebb** [comment]
I was thinking something like secret gists. Generate a GUID for the entry then, if enabled for a post, access using a URL such as `http://spring.io/blog/88e6ca0c353ae21d2b83`.

**Comment by philwebb** [comment]
Actually, it's probably a bad idea and not often needed. I'll close this one.
