### ISSUE TITLE
Link to spring-data-elasticsearch is broken on spring-data project site

### ISSUE THREAD

**Issue by Riggs333** [spring-io/sagan#614]
On this page http://projects.spring.io/spring-data/ under "Community modules" the link for "Spring Data Elasticsearch" points to http://projects.spring.io/spring-data-elasticsearch that currently which leads to a 404.
Should it point to https://github.com/spring-projects/spring-data-elasticsearch?

**Comment by bclozel** [comment]
I've pinged the spring-data team about this and they fixed the link.
Thanks for this report!
