### ISSUE TITLE
Spring Cloud Reference/API Links are Inconsistent

### ISSUE THREAD

**Issue by andersonkyle** [spring-io/sagan#617]
#### I've noticed a lot of inconsistencies with the Reference and API links for Spring Cloud projects.

**Findings**
- Reference links for _most_ of the Spring Cloud projects don't account for the specific release version you're selecting.  The links are the same URL for each release version for most Spring Cloud projects.
- API links for _most_ of the Spring Cloud projects point to their respective GitHub repos instead of their Javadoc like other Spring projects.
- spring-cloud-bus reference links point to the project page instead of the documentation.
- spring-cloud-cluster project page link points to the main spring-cloud project page.  no reference or api links.
- spring-cloud-starters, spring-cloud-cli project page links point to their respective GitHub repos.
- spring-cloud-dataflow, spring-cloud-stream-modules api link for the 1.0.0 M2 release is broken
- spring-cloud-zookeeper api links point to the same documentation as the reference links.
- Inconsistent use of docs & cloud sub-domains.

I've compiled a table of the reference and api links for all Spring Cloud projects.  The links were gathered from each project page.

![image](https://cloud.githubusercontent.com/assets/7154425/12519210/43a2afb6-c0f2-11e5-9b92-6918265d62e5.png)

**Comment by bclozel** [comment]
I think this has been fixed in the meantime by the Spring Cloud team. The documentation has also moved to docs.spring.io now.
