### ISSUE TITLE
"tags" aren't getting rendered on spring.io/guides

### ISSUE THREAD

**Issue by gregturn** [spring-io/sagan#618]
On the page listing all the guides, each entry looks like this:

```
<div class="guide--container" data-filterable="Uploading Files Learn how to build a Spring application that accepts multi-part file uploads. []">
<a class="guide--title" href="/guides/gs/uploading-files/">Uploading Files</a>
<p class="guide--subtitle">Learn how to build a Spring application that accepts multi-part file uploads.</p>
</div>
```

The square brackets are supposed to contain a given guide's tags in order to support filtering. As shown in the fragment taken from the page, it's empty.

The template shows where it's supposed to get put:

https://github.com/spring-io/sagan/blob/master/sagan-site/src/main/resources/templates/guides/index.html#L38-L41

**Comment by bclozel** [comment]
duplicates #574
