### ISSUE TITLE
BlogAuthorTests failed

### ISSUE THREAD

**Issue by Sudip7** [spring-io/sagan#620]
@bclozel: I merged the latest build with my copy. Then I tried to run the build, but, this time, m getting the different type of error. Please find the error logs:

Note: C:\Users\Sudip7\sagan\sagan-site\src\it\java\sagan\team\support\EditTeamMemberTests.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:sagan-site:processIntegTestResources UP-TO-DATE
:sagan-site:integTestClasses
:sagan-site:integTest

sagan.blog.support.BlogAuthorTests > blogIndexPostsIncludeLinkToAuthor FAILED
java.lang.NullPointerException at BlogAuthorTests.java:39

sagan.blog.support.BlogAuthorTests > blogIndexPostsDoNotIncludeLinksToHiddenAuthors FAILED
java.lang.AssertionError at BlogAuthorTests.java:54

sagan.blog.support.BlogAuthorTests > blogPostPageIncludesLinkToAuthor FAILED
java.lang.NullPointerException at BlogAuthorTests.java:67

173 tests completed, 3 failed, 10 skipped
:sagan-site:integTest FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':sagan-site:integTest'.

There were failing tests. See the report at file:///C:/Users/Sudip7/sagan/sagan-site/build/reports/integTest/index.html
Try:
Run with --stack trace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 50.369 secs

**Comment by bclozel** [comment]
Could you add more information?
Running the same command with `--stacktrace` or providing me with the details you're seeing ont the HTML test report should work fine.

**Comment by Sudip7** [comment]
@bclozel : What changed I don't know but there is no more build error. Also I would like to know how could I debug the project/test case in STS. I know your time is valuable but if you could provide the steps that would b really helpful.

**Comment by bclozel** [comment]
If you're using Eclipse, you can right click on the `SiteApplication` class and select "Run As" -> "Java Application" (or debug, if you want to debug).

**Comment by Sudip7** [comment]
@bclozel: is there any way to attach the screenshot , as m not able to create the run configuration for java application: reason - Main type not found and blank/disable pop up for Project selection field.

**Comment by Sudip7** [comment]
@bclozel:ent.com/assets/6715793/12790237/572490b6-cac7-11e5-86e4-0ceae78378c4.jpg)
STS, please find the screenshot attached.

![run_config](https://cloud.githubusercontent.com/assets/6715793/12790261/7a2a10cc-cac7-11e5-84c1-1334ce8d3cd3.jpg)

**Comment by Sudip7** [comment]
![run_config](https://cloud.githubusercontent.com/assets/6715793/12790368/f1606146-cac7-11e5-85c1-4ce60d832c31.jpg)

**Comment by zolbayars** [comment]
My tests got failed too. Exactly like this. But when I tried to build it again the build went SUCCESSFUL
