### ISSUE TITLE
Can't run the site locally from IDE

### ISSUE THREAD

**Issue by zolbayars** [spring-io/sagan#621]
In the wiki it said _"Create a new run configuration with the class sagan.SiteApplication. "_ . Well, **How**? 
(It would be most appreciated if someone could provide "step by step" guide on this)

**Comment by bclozel** [comment]
What IDE are you using?
Usually it's just a matter of running the `public static void main()` method in that class, by right-clicking on the method or class and selecting "run".

**Comment by zolbayars** [comment]
I am using Spring Tool Suite. 
When I right click on this and select Run As it only shows run configuration
![1](https://cloud.githubusercontent.com/assets/3589907/12799073/eadefe5a-cb07-11e5-9f3c-2c43917b4c42.PNG) 

Which one of the following should I choose? 
![2](https://cloud.githubusercontent.com/assets/3589907/12799074/eae103d0-cb07-11e5-9215-620efc344c88.PNG)
I tried Spring boot app. But it threw a nullpointerexception.

**Comment by Sudip7** [comment]
I am facing the same problem. M not able to create new run config as there is no main class selected.

**Comment by Sudip7** [comment]
https://cloud.githubusercontent.com/assets/6715793/12790368/f1606146-cac7-11e5-85c1-4ce60d832c31.jpg

**Comment by zolbayars** [comment]
Maybe the project facet was the cause. When I created the sample spring boot app, there's small 'S' on the icon of java files. But in sagan app there's no 'S' and icon is somewhat different. 

![11](https://cloud.githubusercontent.com/assets/3589907/13687891/2d2858ac-e759-11e5-817a-509ca3f45609.PNG)
![12](https://cloud.githubusercontent.com/assets/3589907/13687918/4c54767a-e759-11e5-8119-823f33113794.PNG)

**Comment by zolbayars** [comment]
Well, At last I was I able to run it on Intellij IDEA. @Sudip7 
1. Import it into _Intellij IDEA_ 
2. Click on _Run_ from the top menu. (_Edit configuration_ button will appear)
3. Get into _Edit configuration_ 
4. Choose _Spring Boot_ from the left side menu (Click on _Defaults_ to collapse it)
5. Set Main class as _sagan.SiteApplication_
6. Choose _sagan-site_ folder as working directory
7. Use _sagan-site_main_ as classpath of module 
8. Then **Run**!
