### ISSUE TITLE
travis CI build failure for my forked copy

### ISSUE THREAD

**Issue by Sudip7** [spring-io/sagan#622]
Hi all,

I got travis build error for my latest build. I understood to change the credentials for cloud foundery but where and how I don't know. Please find the logs:

FAILURE: Build failed with an exception.
* Where:
Script '/home/travis/build/Sudip7/sagan/gradle/deploy.gradle' line: 120
* What went wrong:
Failed to notify task execution graph listener.
> Missing required variable(s) for the 'cfLogin' task: [cfUsername, cfPassword]. Specify them with -Pkey=value or in /home/travis/.gradle/sagan-env.gradle
> Missing required variable(s) for the 'cfLogin' task: [cfUsername, cfPassword]. Specify them with -Pkey=value or in /home/travis/.gradle/sagan-env.gradle
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 11.311 secs
The command "if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./gradlew deploy; else ./gradlew check; fi" exited with 1.
before_cache
0.00s$ rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache.2
store build cache
0.00s
20.43schanges detected, packing new archive
.
uploading archive
Done. Your build exited with 1.

**Comment by bclozel** [comment]
So you want to set up a continuous deployment for your fork?

If you do, you need to configure secret variables in your Travis configuration (top right button on travis-ci, "settings"). Right now I've got several CI environment variables set up for this CI:

![image](https://cloud.githubusercontent.com/assets/103264/12777234/d6d7f968-ca5b-11e5-8a1f-3cea279dc561.png)

**Comment by Sudip7** [comment]
As per above error I may need cfUsername and cfPassword, so what would be those pair. Do I need to create an account in cloud foundry or I can use GitHub credentials!!!

**Comment by bclozel** [comment]
I guess you don't want to set up your fork to continuously deploy to Pivotal Web Services.
In that case, you can clean the Travis file and "just" have a regular CI:

```yml
language: java
jdk:
- oraclejdk8
node_js:
- '0.10'
git:
  submodules: false
sudo: false
```

If you're interested in setting up Sagan in Cloud Foundry, [the wiki has a lot of information on this](https://github.com/spring-io/sagan/wiki).
