### ISSUE TITLE
Empty blog screen while running locally 

### ISSUE THREAD

**Issue by Sudip7** [spring-io/sagan#623]
Hi,
I don't know whether it is issue or configuration mismatch, but I found the different screen for blog window while running the app locally.

**Comment by Sudip7** [comment]
![localscreen](https://cloud.githubusercontent.com/assets/6715793/12790632/4375d1ae-cac9-11e5-9e49-9273371dfe37.jpg)

**Comment by bclozel** [comment]
That's because your database is empty.
You can create new blog posts by logging in the admin http://localhost:8080/admin
