### ISSUE TITLE
New CSS Section Classes on main page 

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#630]
in the RUN ANYWHERE section, can you replace the word PaaS with Cloud?  
Keep it portable – Spring-based apps run anywhere the JVM does. Deploy standalone, in an app server, on a PaaS or all of the above.

** new CSS Section Classes **
1.) spring initializr - (moved out of rotating ad banner) 
place it below ad rotator and above guides

Copy:  
Initalizr
Bootstrap your Spring Boot application with start.spring.io.  Generate a starter project ZIP in seconds for Maven or Gradle and get coding!

Generate now >
http://start.spring.io
background color/image: use light green background like STS section so it's consistent

2.) Spring Certification
place it below spring projects and above "community/professional support" section

Copy:  
Certification
The perfect way to demonstrate your proficiency with the Spring IO Platform portfolio is to obtain an industry-recognized Pivotal Certification. Our role-based certification exams are designed to test and validate your product knowledge and help you advance your career.

Learn More >
http://spring.io/blog/2016/01/21/pivotal-academy-launches-updated-spring-classes
background color/image: use light green background like STS section so it's consistent
background image:  in process

**Comment by pieterhumphrey** [comment]
image for #2 above is here:
https://www.dropbox.com/s/o9nu076xutiyl0j/3104-0316-SPRING-CERT-BANNER_v2-08.jpg?dl=0

**Comment by bclozel** [comment]
Hey Pieter,
Do you want the whole image to be a link?
If not, could you provide me with the background image only? I'll take care of the text + link (probably a better SEO practice anyway).
