### ISSUE TITLE
Floating JS toolbar on docs site update

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#632]
https://github.com/pivotalsoftware/docsearchbar

1.) add this toolbar to all cloud.spring.io API and reference documentation
2.) duplicate spring.io TOPNAV:  GUIDES, PROJECTS, BLOG, QUESTIONS, VIDEOS
3.) add a PWS text only ad (separated from topnav duplication) for deploying on PWS for spring in the footer JS toolbar: “Spring App Hosting” -> http://run.pivotal.io/spring

**Comment by bclozel** [comment]
This toolbar is now gone.
