### ISSUE TITLE
Setting the current version flag requires to set it twice.

### ISSUE THREAD

**Issue by mp911de** [spring-io/sagan#638]
Setting the `current` version flag requires to set it twice to save the `current` flag.

**Comment by mp911de** [comment]
Not able to set current version for Spring Data (spring-data) Hopper-RELEASE at all.

**Comment by bclozel** [comment]
Strange; I don't know what happened.
I had to delete that entry and re-create it manually. It works now.

**Comment by mp911de** [comment]
thx
