### ISSUE TITLE
create trademark page and site footer link

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#645]
please create a static page to host this content:

https://docs.google.com/document/d/1ZtZoZXyTYgZLaWh5JSPIIiQ8UT0kkp1pOBYCIauxgso/edit#

and link to it from the global site footer:
© 2016 Pivotal Software, Inc. All Rights Reserved. Terms of Use and Privacy

Please have it read:
© 2016 Pivotal Software, Inc. All Rights Reserved. Terms of Use, Privacy, Trademark Guidelines

and have "trademark guidelines" link to this static page.

**Comment by bclozel** [comment]
Fixed by #655
