### ISSUE TITLE
Filter on guides not selecting tagged content

### ISSUE THREAD

**Issue by dsyer** [spring-io/sagan#649]
E.g. https://spring.io/guides?filter=security only brings back 2 results, but I know for a fact that at least 4 guides have the "security" tag.

**Comment by gregturn** [comment]
Duplicates #618

**Comment by dsyer** [comment]
Seems like that issue is related, but not a duplicate (this one is about the search query result).

**Comment by gregturn** [comment]
The filter code uses all content rendered on the page. If the "tags" were rendering properly on the page as described in #618 then the filter would work as expected.

**Comment by bclozel** [comment]
Yes, this duplicates #618
