### ISSUE TITLE
Fix remote includes in asciidoctor support

### ISSUE THREAD

**Issue by bclozel** [spring-io/sagan#651]
Many guides, including the [REST service](https://github.com/spring-guides/gs-rest-service) are including common sections (e.g. "what you'll need") as macros.

Those are included as http URLs in the main document. This feature hasn't been working since the 1.5.4 upgrade.

**Comment by gregturn** [comment]
Did we report this to @lordofjars?

**Comment by bclozel** [comment]
Not yet - I have to create a repro project first.

**Comment by bclozel** [comment]
Here: https://github.com/asciidoctor/asciidoctorj/issues/460
