### ISSUE TITLE
403 error page in Latin!

### ISSUE THREAD

**Issue by paulc4** [spring-io/sagan#656]
I tried accessing the admin pages after my login had timed out and the 403 page returned is some generic template in Latin.

<img width="944" alt="screen shot 2016-05-22 at 11 32 33 pm" src="https://cloud.githubusercontent.com/assets/1644418/15454233/f122f640-2075-11e6-9337-0c83fb704aca.png">

**Comment by bclozel** [comment]
This has been fixed with the recent website redesign. Thanks!
