### ISSUE TITLE
Build error on Ubuntu Trusty

### ISSUE THREAD

**Issue by dotku** [spring-io/sagan#658]
> java.lang.UnsupportedClassVersionError: com/gorylenko/GitPropertiesPlugin : Unsupported major.minor version 52.0

I was trying to build the code with command `sudo ./gradlew build`, but I got error with the message above.

**Comment by dotku** [comment]
I found the solution, it require JDK 1.8

**Comment by bclozel** [comment]
Indeed, [Sagan requires JDK8 minimum](https://github.com/spring-io/sagan/wiki/Set-up-environment).
