### ISSUE TITLE
Ubuntu build error with following message

### ISSUE THREAD

**Issue by dotku** [spring-io/sagan#659]
> Process 'command '/home/vagrant/.gradle/nodejs/node-v4.2.2-linux-x64/bin/node'' finished with non-zero exit value 137

**Comment by bclozel** [comment]
Could you add the `--stacktrace` option to your gradlew command and share the output?

**Comment by dotku** [comment]
@bclozel  Here is my trace report

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':sagan-client:npmInstall'.
> > Process 'command '/home/vagrant/.gradle/nodejs/node-v4.2.2-linux-x64/bin/node'                                                                             ' finished with non-zero exit value 1
> 
> * Try:
> Run with --info or --debug option to get more log output.
> 
> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sagan-c                                                                             lient:npmInstall'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                             ecuteActions(ExecuteActionsTaskExecuter.java:69)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                             ecute(ExecuteActionsTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec                                                                             uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec                                                                             ute(SkipUpToDateTaskExecuter.java:68)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut                                                                             e(ValidatingTaskExecuter.java:58)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu                                                                             ter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter                                                                             .execute(SkipTaskWithNoActionsExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut                                                                             e(SkipOnlyIfTaskExecuter.java:53)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter                                                                             .execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa                                                                             skWorker.execute(DefaultTaskGraphExecuter.java:203)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa                                                                             skWorker.execute(DefaultTaskGraphExecuter.java:185)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW                                                                             orker.processTask(AbstractTaskPlanExecutor.java:66)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW                                                                             orker.run(AbstractTaskPlanExecutor.java:50)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul                                                                             tTaskPlanExecutor.java:25)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau                                                                             ltTaskGraphExecuter.java:110)
>         at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask                                                                             ExecutionAction.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute                                                                             r.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExec                                                                             uter.java:23)
>         at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu                                                                             ter.java:43)
>         at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx                                                                             ecutionAction.java:32)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute                                                                             r.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute                                                                             r.java:30)
>         at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLa                                                                             uncher.java:154)
>         at org.gradle.internal.Factories$1.create(Factories.java:22)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                             tBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                             tBuildOperationExecutor.java:52)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default                                                                             GradleLauncher.java:151)
>         at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra                                                                             dleLauncher.java:32)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl                                                                             eLauncher.java:99)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl                                                                             eLauncher.java:93)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                             tBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                             tBuildOperationExecutor.java:62)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle                                                                             Launcher.java:93)
>         at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun                                                                             cher.java:82)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon                                                                             troller.run(InProcessBuildActionExecuter.java:94)
>         at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe                                                                             cuteBuildActionRunner.java:28)
>         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA                                                                             ctionRunner.java:35)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce                                                                             ssBuildActionExecuter.java:43)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce                                                                             ssBuildActionExecuter.java:28)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin                                                                             uousBuildActionExecuter.java:81)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin                                                                             uousBuildActionExecuter.java:46)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe                                                                             cute(DaemonUsageSuggestingBuildActionExecuter.java:51)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe                                                                             cute(DaemonUsageSuggestingBuildActionExecuter.java:28)
>         at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
>         at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav                                                                             a:173)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.                                                                             execute(CommandLineActionFactory.java:241)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.                                                                             execute(CommandLineActionFactory.java:214)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti                                                                             meValidationAction.java:35)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti                                                                             meValidationAction.java:24)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(                                                                             CommandLineActionFactory.java:207)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(                                                                             CommandLineActionFactory.java:169)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep                                                                             ortingAction.java:33)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep                                                                             ortingAction.java:22)
>         at org.gradle.launcher.Main.doAction(Main.java:33)
>         at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots                                                                             trap.java:55)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j                                                                             ava:36)
>         at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
>         at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja                                                                             va:30)
>         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
>         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Caused by: org.gradle.process.internal.ExecException: Process 'command '/home/va                                                                             grant/.gradle/nodejs/node-v4.2.2-linux-x64/bin/node'' finished with non-zero exi                                                                             t value 1
>         at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo                                                                             rmalExitValue(DefaultExecHandle.java:367)
>         at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecActi                                                                             on.java:31)
>         at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOp                                                                             erations.java:176)
>         at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.                                                                             java:841)
>         at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.                                                                             java:837)
>         at org.gradle.api.Project$exec$5.call(Unknown Source)
>         at com.moowork.gradle.node.exec.ExecRunner.run(ExecRunner.groovy:43)
>         at com.moowork.gradle.node.exec.NodeExecRunner.doExecute(NodeExecRunner.                                                                             groovy:44)
>         at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:83)
>         at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
>         at com.moowork.gradle.node.exec.NpmExecRunner.doExecute(NpmExecRunner.gr                                                                             oovy:37)
>         at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:83)
>         at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
>         at com.moowork.gradle.node.task.NpmTask.exec(NpmTask.groovy:74)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF                                                                             actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF                                                                             actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF                                                                             actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra                                                                             ctTask.java:585)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra                                                                             ctTask.java:568)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                             ecuteAction(ExecuteActionsTaskExecuter.java:80)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                             ecuteActions(ExecuteActionsTaskExecuter.java:61)
>         ... 60 more
> 
> 
> BUILD FAILED
> 
> Total time: 25.193 secs
>

**Comment by bclozel** [comment]
Too bad, this doesn't say much about the error...

Is `git` available in the console PATH?
By any chance, do you have node/npm installed on this VM? Could you run the `npm install` command in the `sagan-client` folder? (if you don't have it , you can check [nvm](https://github.com/creationix/nvm) which is pretty useful).

**Comment by dotku** [comment]
@bclozel Yes, you are right, npm is missing, but after I reinstall npm I still have some error:

> vagrant@vagrant-ubuntu-trusty-64:~/githost/sagan$ ./gradlew build
> :sagan-client:compileJava UP-TO-DATE
> :sagan-client:processResources UP-TO-DATE
> :sagan-client:classes UP-TO-DATE
> :sagan-client:nodeSetup UP-TO-DATE
> :sagan-client:npmSetup UP-TO-DATE
> :sagan-client:npmInstall
> npm WARN package.json sagan@ No license field.
> npm WARN prefer global npm@2.14.7 should be installed with -g
> 
> > sagan@ prepublish /home/vagrant/githost/sagan/sagan-client
> > jspm install
> 
> sh: 1: jspm: not found
> 
> npm ERR! Linux 3.13.0-87-generic
> npm ERR! argv "/home/vagrant/.gradle/nodejs/node-v4.2.2-linux-x64/bin/node" "/home/vagrant/githost/sagan/sagan-client/node_modules/npm/bin/npm-cli.js" "install"
> npm ERR! node v4.2.2
> npm ERR! npm  v2.14.7
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! sagan@ prepublish: `jspm install`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the sagan@ prepublish script 'jspm install'.
> npm ERR! This is most likely a problem with the sagan package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     jspm install
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls sagan
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/vagrant/githost/sagan/sagan-client/npm-debug.log
> :sagan-client:npmInstall FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':sagan-client:npmInstall'.
> > Process 'command '/home/vagrant/.gradle/nodejs/node-v4.2.2-linux-x64/bin/node'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 43.209 secs
>

**Comment by bclozel** [comment]
No, I meant "what happens if you run `npm install` manually"?
It seems the main issue is that the gradle-node-plugin can't execute the installed binaries such as `npm` or `jspm`.

You shouldn't need to install `node` or `npm` locally, it's done automatically for you - and it's working fine on [our CI build](https://travis-ci.org/spring-io/sagan). 

Could you check that you have the following files?

```
➜  sagan git:(master) ls -ls sagan-client/node_modules/.bin
gulp -> ../gulp-cli/bin/gulp.js
jspm -> ../jspm/jspm.js
npm -> ../npm/bin/npm-cli.js
```

**Comment by renzhe00** [comment]
@bclozel I meet encountered the same problem. I don't run the `npm install` command in the `sagan-client` folder.

**Comment by renzhe00** [comment]
@bclozel I meet the same problem. I don't run the `npm install` command in the `sagan-client` folder

**Comment by bclozel** [comment]
We've moved away from JSPM and now we're using webpack with a different (hopefully more resilient setup). I'm closing this issue as a result. Thanks!

**Comment by suvDev** [comment]
@bclozel Is there any documentation for the setup, I am having hard time even starting this project.

**Comment by bclozel** [comment]
@suvDev yes, see https://github.com/spring-io/sagan/wiki
