### ISSUE TITLE
SVG badge for spring-cloud has wrong version

### ISSUE THREAD

**Issue by dsyer** [spring-io/sagan#662]
https://spring.io/badges/spring-cloud/ga.svg (or https://spring.io/badges/spring-cloud.svg) shows "Angel.SR6" as the GA version (should be Brixton.SR2).

**Comment by bclozel** [comment]
Pinging @mp911de in case he's got an idea.
I'll look into it as well.

**Comment by mp911de** [comment]
The badge service picks the first version matching the release type in the same order as they are listed on the admin edit page. The current flag is not taken into account. I'll submit a PR to perform a two-pass selection, to first filter by release type (GA, Milestone, Snapshot) and the most recent flag. If the first pass yields no results, then it would fall back to the mechanism of today.

The version ordering works nicely with numeric version numbers (1.10, 1.9, 1.8) but version names (Evans, Gosling, Hopper) are ordered the other way round.

**Comment by dsyer** [comment]
The widgets on the home page work. I assume they just take the first one in the JSON. I suppose if there is logic in the JavaScript it can't be re-used, but I'd expect it is already there serverside.

**Comment by mp911de** [comment]
On the server side the releases are ordered using `compareTo(String)` and ordered in a second pass numerically reversed if the version contains numbers. The script on the website tries to select the `current` entry otherwise, the first entry is selected.

**Comment by dsyer** [comment]
Surely `4.3.1>3.2.7` lexically and `Brixton>Angel` by the same rule. So I'm not sure those rules are being applied, or else I don't understand the algorithm. In any case it seems it needs to be fixed for badges and project_metadata endpoints (in the same way).

**Comment by dsyer** [comment]
Ah, I just read it again "if the version contains numbers". Why not apply the same rule to all versions. This used to work I thought, so someone must have decided that "if the version contains numbers" was a good idea. Can't think why though.

**Comment by mp911de** [comment]
I missed mentioning one effect. The current ordering results in `Angel-SR6>Brixton-SR2` because it matches `6` vs. `2`. `6` is the first numerical element `Angel-SR6` and so the `6` is treated as if it was a major version identifier.

I'd like to fix that ordering issue, but submitting a PR for the badge issue first. I think I might need the help of @bclozel to understand the rationale for the current sorting to not break things.
