### ISSUE TITLE
Advertisements/Clickbait in Blog Posts

### ISSUE THREAD

**Issue by kanderson450** [spring-io/sagan#673]
When visiting the Spring Blog this morning I noticed an embedded Advertisement/Clickbait widget.

Was this intentionally added?  I really hope not...I hate these things.

![capture](https://cloud.githubusercontent.com/assets/7154425/18174521/ad6c2938-7022-11e6-9aac-388423ff0ccf.PNG)

**Comment by bclozel** [comment]
Thanks for the heads up, it seems disqus added those recently.
I hate these things as well, and they're now deactivated in our account.

> the system may take several minutes to remove your ads

Too bad, I was getting a lot of "high quality content" here.

<img width="656" alt="pencils" src="https://cloud.githubusercontent.com/assets/103264/18175862/598d44cc-7073-11e6-86f2-43effc592870.png">

<img width="657" alt="donkeys" src="https://cloud.githubusercontent.com/assets/103264/18175870/5ee568f0-7073-11e6-8389-2b978027be9f.png">
