### ISSUE TITLE
Books on Spring

### ISSUE THREAD

**Issue by packtpartner** [spring-io/sagan#675]
One of our books is put up on http://docs.spring.io/spring-python/1.2.x/sphinx/html/index.html#

We have published a few more books on spring which we would like to feature on the official project site.
I am sure that addition of a 'books' page under the guides section will be beneficial for the Spring community - http://spring.io/guides 
 
Books & Video:
[Spring Security Essentials](https://www.packtpub.com/application-development/spring-security-essentials)
[Spring Essentials](https://www.packtpub.com/application-development/spring-essentials)
[Spring MVC Cookbook](https://www.packtpub.com/web-development/spring-mvc-cookbook)
[Spring Microservices](https://www.packtpub.com/application-development/spring-microservices)
[Spring MVC Blueprints](https://www.packtpub.com/application-development/spring-mvc-blueprints)
[Spring MVC Beginner's Guide
](https://www.packtpub.com/application-development/spring-mvc-beginner%E2%80%99s-guide) [Learning Spring Boot](https://www.packtpub.com/application-development/learning-spring-boot-video)

@kbastani @bclozel  Can you please help me with this?

**Comment by packtpartner** [comment]
Hi Brian @bclozel 

Looking forward for your advice

**Comment by bclozel** [comment]
Hi,

Each project team is free to feature links to external resources on their project page.
I'm not keen on adding external, non-free, resources on that part of the spring.io website.

Thanks,

**Comment by packtpartner** [comment]
@bclozel thanks for your reply. 
We already have one book featured on the project site.
Creation of a new page on the project site will be of a great help to the Spring community.

Thanks 
Eesha
