### ISSUE TITLE
gradle build error - prepublish 'jspm install'

### ISSUE THREAD

**Issue by vprokop** [spring-io/sagan#679]
The gradlew build exits with the exception :sagan-client:npmInstall FAILED

sagan-client/npm-debug.log states the following errors:

808 info sagan@ Failed to exec prepublish script
809 verbose stack Error: sagan@ prepublish: `jspm install`
809 verbose stack Exit status 1
809 verbose stack     at EventEmitter.<anonymous> (/home/vaclav/sagan/sagan-client/node_modules/npm/lib/utils/lifecycle.js:214:16)
809 verbose stack     at emitTwo (events.js:87:13)
809 verbose stack     at EventEmitter.emit (events.js:172:7)
809 verbose stack     at ChildProcess.<anonymous> (/home/vaclav/sagan/sagan-client/node_modules/npm/lib/utils/spawn.js:24:14)
809 verbose stack     at emitTwo (events.js:87:13)
809 verbose stack     at ChildProcess.emit (events.js:172:7)
809 verbose stack     at maybeClose (internal/child_process.js:818:16)
809 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
810 verbose pkgid sagan@
811 verbose cwd /home/vaclav/sagan/sagan-client
812 error Linux 3.13.0-67-generic
813 error argv "/home/vaclav/sagan/sagan-client/.gradle/nodejs/node-v4.2.2-linux-x86/bin/node" "/home/vaclav/sagan/sagan-client/node_modules/npm/bin/npm-cli.js" "install"
814 error node v4.2.2
815 error npm  v2.14.7
816 error code ELIFECYCLE
817 error sagan@ prepublish: `jspm install`
817 error Exit status 1
818 error Failed at the sagan@ prepublish script 'jspm install'.
818 error This is most likely a problem with the sagan package,
818 error not with npm itself.
818 error Tell the author that this fails on your system:
818 error     jspm install
818 error You can get their info via:
818 error     npm owner ls sagan
818 error There is likely additional logging output above.

Would you reccomend me next steps to take to resolve the issue? Thank you. Vaclav

**Comment by satansk** [comment]
I have encountered this problem on mac, and maybe it triggered by jspm.

**Comment by satansk** [comment]
I have solved this problem by npm install & npm build in the sagan-client directory and then run ./gradlew build in the sagan directory, hope this will help you.

**Comment by renzhe00** [comment]
@satansk I don't run `npm install & npm build` in sagan-client directory.
-

**Comment by renzhe00** [comment]
@satansk I don't run npm install & npm build in sagan-client directory.

**Comment by bclozel** [comment]
We've moved away from JSPM and now we're using webpack with a different (hopefully more resilient setup). I'm closing this issue as a result. Thanks!
