### ISSUE TITLE
ask@spring.io email doesn't work

### ISSUE THREAD

**Issue by philwebb** [spring-io/sagan#680]
According to https://twitter.com/schultzdustin/status/785995115152052228

**Comment by trevormarshall** [comment]
The email address doesn't exist, and never has. The domain doesn't keep a MX record.

**Comment by bclozel** [comment]
@pieterhumphrey @gregturn could you tell us more about this? What's the email address we should list here?

**Comment by gregturn** [comment]
Presumably we should either

A) switch it to ask@pivotal.io (another spring by pivotal opportunity) and coach the help desk to route site issues to a list of maintainers. 

Or

B) setup such an address and perhaps make it a distribution list to the same people from (A). 

I reckon short list of people on such a list should include Brian, Trevor, myself, Dave Syer?, and ???

**Comment by bclozel** [comment]
This address is listed on the [trademarks page](https://spring.io/trademarks) - we need to route those requests to people in charge of those trademark guidelines.

**Comment by pieterhumphrey** [comment]
requesting trevor to create the MX record.

**Comment by trevormarshall** [comment]
The ask@spring.io email alias was created in June 2017 and routes to folks inside Pivotal.
