### ISSUE TITLE
update to hero banner on homepage

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#682]
can we add this into the rotation?  

![jaxde2016_innovation_award_boot](https://cloud.githubusercontent.com/assets/959913/19571142/d555474e-96b1-11e6-98f5-3ab191f19995.jpg)

image should link to 
https://spring.io/blog/2016/10/11/spring-boot-wins-jax-innovation-award-for-2016

**Comment by pieterhumphrey** [comment]
one additional one I've been meaning to make for awhile, can you update the spring cloud brixton ad banner copy?  same design.  Thank you!

Updated text:
Spring Cloud Camden adds Consumer Driven Contracts, Service Schemas, and much more

**Comment by bclozel** [comment]
Done!
