### ISSUE TITLE
integrate Spring Tip video from Josh about STS into tooling page

### ISSUE THREAD

**Issue by martinlippert** [spring-io/sagan#689]
Josh recorded this Spring Tip video about STS (https://spring.io/blog/2016/12/21/spring-tips-spring-tool-suite), which is also a nice general introduction into the Spring Tool Suite (from the Spring Boot perspective, which is great). It would be great if we could integrate it into the tools web page.

Not sure yet where exactly to place it, but I am sure we will find a good spot for it.

**Comment by martinlippert** [comment]
We could put it onto the https://spring.io/tools/sts page, between the general intro paragraph and the first feature section

Another alternative would be https://spring.io/tools, but that might confuse the overall layout of that page quite a bit.

**Comment by bclozel** [comment]
the tools page has been refreshed and the legacy ones are about to be retired.
