### ISSUE TITLE
spring-security landing page is broken when visiting over https

### ISSUE THREAD

**Issue by abatkin** [spring-io/sagan#690]
When visiting the Spring Security landing page over https (https://projects.spring.io/spring-security/) much of the page content is missing. When visiting over plain http (http://projects.spring.io/spring-security/) everything works fine.

Tested in Firefox 50.1.0 and Chrome 55.0.2883.87 under Linux

See spring-io/sagan#678

**Comment by bclozel** [comment]
I've raised spring-projects/spring-security#4185 to fix this.
Thanks for the report!
