### ISSUE TITLE
add hero banner to spring.io for Spring on PWS

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#692]
Could you add in the last rotation position please?

Example banner with copy
![springio_hero_pws](https://cloud.githubusercontent.com/assets/959913/22265456/f5508f02-e230-11e6-9d67-f9c923281337.png)

File for your use on the website, without text
https://www.dropbox.com/s/6sjhvwigpwlgtax/Pivotal-Spring-Hero-Banner-PWS-f1-JP.png?dl=0

**Comment by bclozel** [comment]
@pieterhumphrey where should the link point to?

**Comment by pieterhumphrey** [comment]
ha!  apologies, link goes to http://run.pivotal.io/spring

**Comment by pieterhumphrey** [comment]
Brian, can we fix the formatting on this banner?   I only find it to happen when on smaller 4:3 monitors, less so 16:9.  Available for any tests.

**Comment by bclozel** [comment]
I thought I did with b847894ba3d - I'll have to reproduce that locally - any hint on how to do that?

**Comment by pieterhumphrey** [comment]
actually it is happening on 16:9 as well.   Do you not see this behavior on your machine?

**Comment by pieterhumphrey** [comment]
try doing it on different screen aspects and re-sizing browser window, it shouldn't take you long at all to reproduce
