### ISSUE TITLE
How does Sagan merge Javascript sources on ./gradlew bootRun?

### ISSUE THREAD

**Issue by arminnaderi** [spring-io/sagan#693]
In the documentation of sagan-client it was mentioned that the run configuration working directory needs to be set to sagan-site, however I do not see any code in both of these modules that allows this to work. I do understand that on `./gradlew build` the client sources get merged into the jar file, however for bootRun the bytecode is ran and the client assets are not in the /static or /public directory.

Any clarification would be greatly appreciated. Thank you for reading this.

**Comment by bclozel** [comment]
At development time, client sources aren't optimized/packaged as a webjar into the sagan-site module. The configuration is merely pointing at those resources and configuring devtools to trigger reloads whenever those files are changed. See [this part of the application configuration](https://github.com/spring-io/sagan/blob/master/sagan-site/src/main/resources/application.yml#L115-L124).
