### ISSUE TITLE
add newly minted logo to spring statemachine page

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#695]
can we add the logo 
https://drive.google.com/a/pivotal.io/file/d/0B7akieR6dYsubWNVZG5ySFJkUDI2V3RYQWgtajFsalQzbnhV/view?usp=sharing

for spring statemachine to the project page?
https://projects.spring.io/spring-statemachine/

It doens't look like statemachine appears on spring.io/projects so I think that's the only place it shows up.

**Comment by jvalkeal** [comment]
Yeah I started to get some questions why it's not on our projects page. I'm happy if we get it at the bottom next to Spring Kafka.

**Comment by jvalkeal** [comment]
Paging @bclozel, would you have time to look at this issue?

**Comment by bclozel** [comment]
I'll add it on our projects page.

Note that the missing logo on https://projects.spring.io/spring-statemachine/ is not Sagan, but the project itself. @jvalkeal, you can deal with that in the [gh-pages branch of the repo](https://github.com/spring-projects/spring-statemachine/tree/gh-pages).

**Comment by jvalkeal** [comment]
Right ok, didn't realise until now that projects pages may also have logos(as those are rather shaded in a background). But yeah, need your help as I believe that iconsprite is managed by sagan, right?

**Comment by bclozel** [comment]
It's not part of the sprite, it's a separate file. Do you have that logo variant?
Here's the Boot one for example: http://projects.spring.io/spring-boot/img/project-icon-large.png

**Comment by jvalkeal** [comment]
yes, I'll handle project page itself. For iconsprite I just meant that logos in spring.io/projects are coming from that sprite.

**Comment by bclozel** [comment]
See https://github.com/spring-projects/spring-statemachine/pull/328 for a quick update since that branch is a bit behind the reference repository.

**Comment by jvalkeal** [comment]
oh, cool. thx a lot :)

**Comment by jvalkeal** [comment]
Hmm, now that I look it closer I only received png, ai and eps files without variants.

**Comment by jvalkeal** [comment]
ok, I modified that icon myself and put it in place.

**Comment by jvalkeal** [comment]
@bclozel when do you have a plan to tweak that projects page?

**Comment by bclozel** [comment]
This is now live - sorry about the delay, we've had quite a few issues with the CI and integrating other PRs.

**Comment by jvalkeal** [comment]
@bclozel logo on spring.io/projects is wrong way around. Logo should have S shape in it but for some reason S is a mirror image and should be fixed. People who made that logo pointed it out. Logo I put to http://projects.spring.io/spring-statemachine is correct.
