### ISSUE TITLE
update existing hero banner

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#697]
for the hero banner that says: AUTOMATE OPS FOR SPRING CLOUD ON CLOUD FOUNDRY

could you update the URL to point to this article?

https://content.pivotal.io/blog/building-spring-microservices-with-cloud-foundrys-new-container-networking-stack

**Comment by kuldeepsidhu88** [comment]
I can work on it.

**Comment by bclozel** [comment]
Fixed by #698
