### ISSUE TITLE
The dependent path has a error in file application.yml

### ISSUE THREAD

**Issue by zhoupenglei** [spring-io/sagan#699]
The Dependent path has a error in file   sagan-site/src/main/resources/application.yml   resources:
    static_locations:
      - file:../sagan-client/src/
  devtools:
    restart:
      additional_paths:
        -. ./sagan-client/src/
## should be :
resources:
    static_locations:
      - file:./sagan-client/src/
  devtools:
    restart:
      additional_paths:
        - ./sagan-client/src/

the path should not has a more dot(.)

**Comment by nirehs** [comment]
right！me too

**Comment by bclozel** [comment]
As described [here](https://github.com/spring-io/sagan/wiki/Import-into-IDEA-or-Eclipse), running from the IDE requires you to configure the `sagan-site` module folder as the working directory. Running `./gradlew :sagan-site:bootRun` from the CLI uses that module as working directory as well.

So for consistency, we're using this configuration to cover both scenarios.
