### ISSUE TITLE
Versions don't get displayed when project sites get accessed with https

### ISSUE THREAD

**Issue by schauder** [spring-io/sagan#722]
I don't see the block showing all the versions when I access 

https://projects.spring.io/spring-data-jpa/

But it is there when I use http instead of https:

http://projects.spring.io/spring-data-jpa/

Tried it with firefox and chrome.

The console displays the following:
```
Mixed Content: The page at 'https://projects.spring.io/spring-data-jpa/' was loaded over HTTPS, but requested an insecure script 'http://spring.io/project_metadata/spring-data-jpa?callback=jQuery110108125174662231085_1493021468525&_=1493021468526'. This request has been blocked; the content must be served over HTTPS.
send @ jquery.js:8534
```

and 

```
play.gopivotal.com/OSS_Website_Spring_SpringNewsletterSubscriptionEmailOnly.html Failed to load resource: net::ERR_INSECURE_RESPONSE
```

**Comment by bclozel** [comment]
This is not related to Sagan, but rather the `gh-pages` branch in that repository not being up to date. Check out https://github.com/spring-projects/gh-pages#how-to-keep-common-gh-pages-content-up-to-date for more information and let me know if you need help updating.

Thanks!
