### ISSUE TITLE
Execution failed for task ':sagan-site:generateGitProperties'

### ISSUE THREAD

**Issue by haojx** [spring-io/sagan#723]
gradle build tell me Execution failed for task ':sagan-site:generateGitProperties'  
what problem?

**Comment by bclozel** [comment]
Did you actually clone the git repository or did you just download the sources?
If you didn't clone the repository that's expected since the project in that case does not contain any git information.

**Comment by bclozel** [comment]
Closing as we didn't get feedback on this.
