### ISSUE TITLE
Generated sagan WAR file not working in Tomcat/JRE 8

### ISSUE THREAD

**Issue by cotjoey** [spring-io/sagan#724]
After following instructions at this URL: https://spring.io/guides/gs/convert-jar-to-war/ , I am unable to generate a '.war' file that loads properly in Tomcat with JRE 8 (I copy the file from <sagan_project_root>/sagan-site/build/libs/sagan-site.war to the Tomcat 'webapps' directory). Tomcat unpacks the .war file, starts it, but the web application won't load. I do not see errors in the logs either. It's almost like it's missing a web.xml, but many posts say it's not required).

The URL leads to the following articles:
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-packaging
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file

... but whatever I put in the build.gradle files, it doesn't generate a working .war file.

I tried setting the values in <sagan_project_root>/sagan-site/build.gradle and also in <sagan_project_root>/build.gradle, without success:

```
apply plugin: 'war'

war {
    baseName = 'myapp'
    version =  '0.5.0'
}

repositories {
    jcenter()
    maven { url "http://repo.spring.io/libs-snapshot" }
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
    ...
}
```

Can someone provide the detailed exact instructions on how to accomplish this for the 'sagan' GitHub project? For Gradle, please.

Thank you.

**Comment by dsyer** [comment]
I don't see anything wrong with the config above. Maybe if you push your attempt up to your fork of this repo someone can see exactly what you tried and suggest a change via a PR?

Did you try the sample in the guide? Does that work for you?

**Comment by cotjoey** [comment]
My fork is available here: https://github.com/cotjoey/sagan
I modified the file: `sagan/sagan-site/build.gradle`

The generated .war file goes into: `sagan/sagan-site/build/libs/sagan-site-1.0.0.war`
When copied into `<tomcat_home>/webapps`, the `catalina.out log` file only says the .war deployment was successful, nothing else:

`08-May-2017 22:44:42.244 INFO [localhost-startStop-2] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /Users/myuser/Documents/IT/apache-tomcat-8.5.14/webapps/sagan-site-1.0.0.war has finished in 13,196 ms`

As per another Spring doc, I tried adding `extends SpringBootServletInitializer`to sagan.SiteApplication.java - That is the only time I saw the SpringBoot logo in the catalina.out log file, but the application failed to load because of:

```
2017-05-09 10:31:52.940  INFO 4822 --- [ost-startStop-4] sagan.SiteApplication                    : No active profile set, falling back to default profiles: default
2017-05-09 10:32:18.574  WARN 4822 --- [ost-startStop-4] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'atomFeedController' defined in file [/Users/myuser/Documents/IT/apache-tomcat-8.5.14/webapps/sagan-site-1.0.0/WEB-INF/classes/sagan/blog/support/AtomFeedController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blogService': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'disqus_shortname' in string value "${disqus_shortname}"
```
Is that extend required for the .war to work in Tomcat?

**Comment by dsyer** [comment]
Well it's a bit more than just adding `extends SpringBootServletInitializer` to the main class. Did you read the guide your linked to (https://spring.io/guides/gs/convert-jar-to-war/)? You said you "followed" the guide, but it seems like maybe you missed the point somewhere. If I were you I'd read it again and see if it makes sense this time.
