### ISSUE TITLE
update certification URL on main spring.io home page

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#725]
Certification
The perfect way to demonstrate your proficiency with the Spring IO Platform portfolio is to obtain an industry-recognized Pivotal Certification. Our role-based certification exams are designed to test and validate your product knowledge and help you advance your career.
Learn more 
https://spring.io/blog/2016/01/21/pivotal-academy-launches-updated-spring-classes

Could you please update this above URL to point to 
https://spring.io/blog/2017/05/10/pivotal-announces-spring-curriculum-certification-changes

**Comment by pieterhumphrey** [comment]
i'm not sure how the team handles assigning people to issues. 
LMK if you'd like me to be doing it differently.

**Comment by bclozel** [comment]
This text doesn't appear on the homepage anymore.
