### ISSUE TITLE
NullPointerException when updating project metadata without submitting apiDocUrl or refDocUrl

### ISSUE THREAD

**Issue by olivergierke** [spring-io/sagan#732]
When posting or putting releases to the `ProjectMetadataController` without an `apiDocUrl` or `refDocUrl` the request fails as the code in `ProjectRelease` assumes it to be never `null`(e.g. in `replaceVersionPattern(…)`. Submitting an empty `String` instead solves the issue.

I guess that stems from the original HTML form always submitting an empty string and the addition of the JSON based controller not taking that scenario into account.

**Comment by bclozel** [comment]
Fixed by #751
