### ISSUE TITLE
Does any plan about supporting gitlab in future exist?

### ISSUE THREAD

**Issue by soiff** [spring-io/sagan#735]
I'm looking for solutions for integrating sagan with our private gitlab server. Would you nice guys please tell me where can I get the idea about this? Any suggest would be appreciate!

**Comment by dsyer** [comment]
We use github, so we don't need to support gitlab. We use github authentication for admin features (so look at how that works in gitlab - maybe they have the same features?), and we use github URIs for grabbing static content for guides (they might also be compatible with gitlab). What did you try and what didn't work?

**Comment by soiff** [comment]
What a nice work for this project. I'm studying the implementation, especially the `Github` definition. And it seems like that the functions in `GistOperations` will not work in gitlab. However, other features should be capable. I've googled the solution and it seems like nobody has ever done this. However. in my scenario, we could only host our repository on a gitlab server, which has limited usage about sagan. But it is really a great start point for our scenario. I'll keep looking for an available solution about this. And we will do necessary development if we have to. Thanks a lot for your reply!

**Comment by gregturn** [comment]
The guides section assumes a certain URI Layout to look up content. We use GitHub APIs to pull down tar balls for asciidoctor. 

All of these things imply points where the app could be altered to support multiple providers. It also sounds like a lot of work, but it could be a good experiment for you. (Hint: I doubt anyone on the Spring team has time to offer such an adaptation)

**Comment by soiff** [comment]
Understood! Thanks any way! It's a really nice start point though there are a lot work to do.
