### ISSUE TITLE
Navigate to a project landing page via the left sidebar

### ISSUE THREAD

**Issue by abdoughr** [spring-io/sagan#752]
I WANT to be able to click on another project from a specific project page
SO that I can discover content and navigate easily

-----------

GIVEN I am on the project page
WHEN I click on the left corner menu
THEN I go to the project page I clicked on

**Comment by gbufrem** [comment]
@karinepires I'm a little confused by this one. When I click on a project's name I am redirected to the old spring.io website to that page. I don't think this was the intended functionality

**Comment by gbufrem** [comment]
Story works well when referring to **boot** as a project, but not towards other projects

**Comment by bclozel** [comment]
This has been fixed - this as merely a problem with project metadata not being up to date while project leads were migrating to the new project pages. Thanks!
