### ISSUE TITLE
Navigate to Initializr via updated Quick Start

### ISSUE THREAD

**Issue by abdoughr** [spring-io/sagan#754]
I WANT to be able to access initializer 
SO that I can kickstart a project and see how it works quickly

------------

GIVEN I am on the project overview page, 
WHEN I click on "Get Started" on the QuickStart section, THEN I am redirected to initalizr

**Comment by bclozel** [comment]
We've now featured start.spring.io on the quickstart page and many other pages on the website. This is now fixed! Thanks!
