### ISSUE TITLE
See updated project header (project name, github, stackoverflow, and current project version)

### ISSUE THREAD

**Issue by abdoughr** [spring-io/sagan#755]
I want to see the project main informations at the top of the page 
SO I can easily check i am in the right place and navigate to main sources of info quicly

----------

GIVEN clicked on a specific project name
WHEN I reach the overview page of that project
THEN I see the name, github + stackoverflow links + current version

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
