### ISSUE TITLE
Navigate to Current Reference Documentation

### ISSUE THREAD

**Issue by abdoughr** [spring-io/sagan#757]
AS an engineer using Spring
I WANT to access the current reference doc for a specific project
SO I can get the information I am looking for to solve my issue

------------

GIVEN I am on the 'learn' section of a project I can see the reference documentation with the current version
WHEN I click on the current reference documentation
THEN I am redirected to the reference documentation

**Comment by gbufrem** [comment]
@abdoughr regarding the acceptance criteria here - aren't we talking about the Project page?

**Comment by karinepires** [comment]
Would that be possible to go directly to docs when clicking on the version? @abdoughr @gbufrem

**Comment by gbufrem** [comment]
Rejected because when I click back from the reference documentation I land on the overview page and not the learn page

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
