### ISSUE TITLE
Navigate to Current API Docs

### ISSUE THREAD

**Issue by abdoughr** [spring-io/sagan#758]
I WANT to access current API doc for a specific project
SO I can get the information I am looking for to solve my issue

GIVEN I am on the 'learn' section of a project
WHEN I click on the API doc
THEN I am redirected to the API documentation

**Comment by gbufrem** [comment]
@abdoughr similar to the previous story - I think here we are referring to the Project Page as the Learn section is lower on the page

**Comment by gbufrem** [comment]
Rejected because when I click back from the reference documentation I land on the overview page and not the learn page

**Comment by gbufrem** [comment]
Rejected because when I click back from the reference documentation I land on the overview page and not the learn page

**Comment by gbufrem** [comment]
Rejected because when I click back from the reference documentation I land on the overview page and not the learn page

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
