### ISSUE TITLE
View updated Samples section with titles, descriptions, links

### ISSUE THREAD

**Issue by abdoughr** [spring-io/sagan#761]
I WANT to discover samples for a specific project
SO I can quickly use examples of specific topics

-------------

GIVEN I am on the overview, learn, or updates page
WHEN I click on the samples page
THEN I see samples with a title, short description and a link to reach them

GIVEN I am on the samples page
WHEN I click on sample
THEN the sample example opens on a new tab

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
