### ISSUE TITLE
Navigate to project within an umbrella project via the left sidebar

### ISSUE THREAD

**Issue by karinepires** [spring-io/sagan#763]
I WANT to be able to click on a sub-project
SO that I can access that content

GIVEN I am on a project page
WHEN I click on a subproject on the left corner menu
THEN I go to the project page I clicked on
+
GIVEN I am on a project page
WHEN I click on an umbrella project
THEN the modules under this project show up automatically
+ 
WHEN I click on the umbrella project arrow
THEN the subproject list is minimized

[this story takes into account that when you click on a project currently you are redirected to that project's page]

**Comment by gbufrem** [comment]
Just updated this story!

**Comment by abdoughr** [comment]
Design :

When the user clicks in an umbrella project the modules under this project show up automatically.
He can click on the arrow to hide them.

umbrella project selected : https://zpl.io/VKGvkNR
Module project selected : https://zpl.io/bz8XDrM
