### ISSUE TITLE
Navigate to related project pages from a guide

### ISSUE THREAD

**Issue by gbufrem** [spring-io/sagan#765]

**Comment by abdoughr** [comment]
Design : 

When the user clicks in an umbrella project the modules under this project show up automatically.
He can click on the arrow to hide them.

umbrella project selected : https://zpl.io/VKGvkNR
Module project selected : https://zpl.io/bz8XDrM

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
