### ISSUE TITLE
View related Topic Guide(s) link(s) with Topical Guide section header if available

### ISSUE THREAD

**Issue by gbufrem** [spring-io/sagan#774]
I WANT to be able to see available topical guides
SO that I can access that specific form of content

GIVEN I am on the learn page
WHEN I scroll down to Topical Guides section
IF there are topical guides available 
THEN I can see the Topical Guides header and the specific topical guides

--------------

Design : https://zpl.io/VKGvkNR

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
