### ISSUE TITLE
Navigate to a specific tutorial

### ISSUE THREAD

**Issue by gbufrem** [spring-io/sagan#780]
I WANT to be able to see available tutorials
SO that I can access that specific form of content 

GIVEN I am on the learn page
WHEN I scroll down to Tutorials section
THEN I can see the Tutorials header and the specific tutorials

WHEN I click on a tutorial
THEN I am redirected to that tutorial's page

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
