### ISSUE TITLE
Navigate to other API Docs

### ISSUE THREAD

**Issue by gbufrem** [spring-io/sagan#786]
AS an engineer using Spring
I WANT to access the all other available API docs for a specific project
SO I can get the information I am looking for to solve my issue

_______________________________________________________________________________________________________

GIVEN I am on the 'learn' section of a project I can see the API documentation with the other versions button
WHEN I click on "other versions"
THEN the box opens to show other available documentation
+
WHEN I click on specific documentation
THEN I that documentation opens on a new tab

**Comment by gbufrem** [comment]
Rejected because when I click back from the reference documentation I land on the overview page and not the learn page

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
