### ISSUE TITLE
STS 3.9.1 release doesn't show up on main tools page

### ISSUE THREAD

**Issue by martinlippert** [spring-io/sagan#788]
After pushing out the STS 3.9.1 release a moment ago, it doesn't show up on the main tools page anymore: https://spring.io/tools.

There used to be a direct download button that points to the platform specific download as a shortcut. The downloads for all platforms on https://spring.io/tools/sts/all render nicely.

I guess this might be related to the format of the Eclipse version, since STS contains an `e4.7.1a` in the name instead of a simple `e4.7.1`. Maybe some pattern matching is going wrong here... :-)

**Comment by martinlippert** [comment]
@bclozel Thanks for the quick turnaround, much much appreciated. So our new DMG file format caused the trouble. Sorry for that.

**Comment by bclozel** [comment]
No problem! Thanks for keeping an eye on this.
