### ISSUE TITLE
Minor update to https://spring.io/understanding/AMQP

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#799]
looking to get "Solace" listed as a broker that supports AMQP here:

https://spring.io/understanding/AMQP

with this hyperlink: http://dev.solace.com/tech/amqp/

request from a partner

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/understanding/commit/96212d0cd3c6169bb180f7c5e17cc7cee0b9eac7
