### ISSUE TITLE
ERROR while executing command "gradlew eclipse" on Windows 10 command prompt

### ISSUE THREAD

**Issue by gavya** [spring-io/sagan#810]
I want to import Segan project into STS. I followed link "https://github.com/spring-io/sagan/wiki/Import-into-IDEA-or-Eclipse".

When I executed command "gradlew eclipse" from command prompt, I am getting error as "java.io.IOException: Unable to delete file: D:\sagan\sagan-site\build\resources\main\git.properties".

Because of error, I deleted "git.properties" file manually. But I got same error, when I tried to execute this again.

How can I fix this error?

**Entire stack trace is :**
D:\sagan>gradlew eclipse
Starting a Gradle Daemon, 1 busy and 4 stopped Daemons could not be reused, use --status for details

> Configure project :
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
        at integTest_am7cp45hvyamzo06qbxoomsd1$_run_closure2.doCall(D:\sagan\gradle\integTest.gradle:26)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
        at integTest_am7cp45hvyamzo06qbxoomsd1$_run_closure2.doCall(D:\sagan\gradle\integTest.gradle:26)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
        at integTest_am7cp45hvyamzo06qbxoomsd1$_run_closure2.doCall(D:\sagan\gradle\integTest.gradle:32)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Configure project :sagan-site
For project [sagan-site] with version [1.0.0.BUILD-SNAPSHOT] the resolved Artifactory repo is [libs-snapshot-local]

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Unable to delete file: D:\sagan\sagan-site\build\resources\main\git.properties
> Unable to delete file: D:\sagan\sagan-site\build\resources\main\git.properties

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
21 actionable tasks: 8 executed, 13 up-to-date

**Comment by gavya** [comment]
[error_log.txt](https://github.com/spring-io/sagan/files/1645966/error_log.txt)

**Comment by bclozel** [comment]
We've removed the eclipse task since, at buildship is the proper way to go now. Thanks!
