### ISSUE TITLE
Fail to run ./gradlew eclipse from the root directory of your sagan repository clone.

### ISSUE THREAD

**Issue by Abbreviation-g** [spring-io/sagan#812]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sagan-client:npmInstall'.
> Process 'command 'D:\eclipse-jee-oxygen-2-win32-x86_64\eclipse\workspace_sagan
\sagan\sagan-client\.gradle\nodejs\node-v4.2.2-windows-x64\bin\node.exe'' finish
ed with non-zero exit value 1

**Comment by dsyer** [comment]
I'd say that was a local network problem. Clear your cache and start again.

**Comment by acoinfo-g** [comment]
i can't access this address blow
http://repo.spring.io/libs-release/org/flywaydb/flyway-core/3.2.1/flyway-core-3.2.1.pom
is there any file missing？

**Comment by acoinfo-g** [comment]
i can't access this address blow
http://repo.spring.io/libs-release/org/flywaydb/flyway-parent/3.2.1/flyway-parent-3.2.1.pom
is there any file missing in server？

**Comment by dsyer** [comment]
Works for me. You must have a network restriction or issue.

**Comment by acoinfo-g** [comment]
All right, I will try again later.
