### ISSUE TITLE
Guide build instructions don't open on an iPad

### ISSUE THREAD

**Issue by mminella** [spring-io/sagan#816]
When attempting to read a guide, the build sections (`Build with Maven`, `Build with Gradle`, etc) don't open on an iPad.  This was tested on a 12.5" iPad Pro using Chrome and Safari.

**Comment by gregturn** [comment]
Another data point: this works on my iPhone when using the safari browser but NOT when using the browser built into tweetbot.

**Comment by wilkinsona** [comment]
It doesn't work for me on iPhone, either directly in Safari or when using the browser that's built into Tweetbot. That's not surprising as both are Safari as Tweetbot uses [SFSafariViewController](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller).

**Comment by bclozel** [comment]
We've redesigned the website since and we're good with mobile and tablets now.
