### ISSUE TITLE
Guide "Building a RESTful Web Service" fails to include code samples

### ISSUE THREAD

**Issue by sn42** [spring-io/sagan#828]
The guide [Building a RESTful Web Service](https://spring.io/guides/gs/rest-service/) fails to include the code samples with the following message:
> Unresolved directive in <stdin> - include::complete/src/main/java/hello/Greeting.java[]
> Unresolved directive in <stdin> - include::complete/src/main/java/hello/GreetingController.java[]
> Unresolved directive in <stdin> - include::complete/src/main/java/hello/Application.java[]

Resulting output:
![sagan_guide_issue](https://user-images.githubusercontent.com/21104385/37869625-339e2e12-2fbb-11e8-9dc5-0e8530b27062.PNG)
Other guides i checked are not affected.

**Comment by bclozel** [comment]
This is now fixed - the guide wasn't properly rendered.
Thanks!
