### ISSUE TITLE
add new global site header item "build" which links to start.spring.io

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-io/sagan#830]
Next to projects / guides / blog, could we add an item, build?

**Comment by pieterhumphrey** [comment]
also, separately, could we add a link to initializr from tjhis copy in the "spring boot" section of the home page?

BUILD ANYTHING WITH SPRING BOOT
Spring Boot is the starting point for building all Spring-based applications. Spring Boot is designed to get you up and running as quickly as possible, with minimal upfront configuration of Spring.

- | Get started in seconds using [[Spring Initializr](https://start.spring.io)]

**Comment by bclozel** [comment]
We've redesigned the website completely and now start.spring.io is featured in many pages in the website, including the new Quickstart page.
