### ISSUE TITLE
Please add Spring Cloud Stream project to spring.io/projects

### ISSUE THREAD

**Issue by olegz** [spring-io/sagan#837]
Please use the existing logo from Spring Cloud Data Flow (for now). I will submit a new logo within week(s).
The project current page is https://cloud.spring.io/spring-cloud-stream/

Please let me know if you require more info.

**Comment by dsyer** [comment]
The other spring cloud projects don’t have a logo/link on the main projects page there (Data Flow is the only exception). Same for Spring Data. Maybe we should stick with that?

**Comment by olegz** [comment]
I guess we can use the spring-cloud logo for now, for both spring-cloud-function and spring-cloud-stream. Should we open up a separate issue for spring-cloud-function as it needs to be added to the page as well?

**Comment by olegz** [comment]
I see, so I guess what you're sayin is that all spring-cloud-* projects must be under some hierarchy of spring-cloud. I guess i can't argue that.

**Comment by olegz** [comment]
Actually I see now. By clicking on spring-cloud you get their main page which lists all the projects including SCSt. That makes sense and may be we can do some more work on spring-cloud project page to increase visibility to those projects, but that's a hole other issue/discussion. 
Nothing needs to be done here, so I am closing it. Sorry for the confusion.
