### ISSUE TITLE
when execute "gradlew :sagan-site:bootrun", get an exception: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal

### ISSUE THREAD

**Issue by SumanthBala** [spring-io/sagan#840]
**when execute "gradlew :sagan-site:bootrun", get an exception: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal,**
-tried of many times but getting the same error , replicated in multiple systems****

**Comment by bclozel** [comment]
I can't reproduce this - could you tell me a bit more so I can try to figure this out?
What's your Java version, operating system? The ouput of `./gradlew --version` should help.

**Comment by bclozel** [comment]
Closing since we couldn't reproduce this and didn't get feedback.
