### ISSUE TITLE
Website page text is blurry in Firefox and Chrome on Windows 7

### ISSUE THREAD

**Issue by Zalathar** [spring-io/sagan#868]
When I view any page on https://spring.io in Firefox on Windows 7, all of the page text is heavy and blurry.

[Example screenshot of this page:](https://spring.io/guides/gs/consuming-web-service/)

![blurry](https://user-images.githubusercontent.com/20290842/48521681-a76fe980-e8c9-11e8-8e9d-78b39020e066.png)

If I use the browser's developer tools to remove the `-webkit-text-stroke` CSS rule from the `<body>` element, the blurriness disappears:

![clear](https://user-images.githubusercontent.com/20290842/48521684-accd3400-e8c9-11e8-81aa-c060b71f178a.png)

----

It looks like there's some [script in the page template](https://github.com/spring-io/sagan/blob/7bb9b526ea2f98c5e3cd78900cc9da756c5350b5/sagan-site/src/main/resources/templates/layout.html#L36-L41) that adds this CSS rule to work around a specific rendering problem in WebKit browsers on Windows 7. But because [Firefox added compatibility support for some `-webkit-` prefixes](https://hacks.mozilla.org/2016/09/firefox-49-fixes-sites-designed-with-webkit-in-mind-and-more/), that workaround is applied in Firefox as well, with unintended results.

(Firefox version: 64.0b9 (64-bit))

**Comment by Zalathar** [comment]
The same behaviour also occurs in Chrome (Version 70.0.3538.102 (Official Build) (64-bit)).

**Comment by bclozel** [comment]
What do you think @oodamien ?

**Comment by bclozel** [comment]
We've redesigned the website, so this issue doesn't apply anymore. Thanks!
