### ISSUE TITLE
Where the PostgreSQL database is used in this project

### ISSUE THREAD

**Issue by WeiXiaoxia** [spring-io/sagan#878]
I'd like to know where the PostgreSQL database is used in this project. So far I've only found H2 data sources. Wiki also introduces the import and export of PostgreSQL database.

**Comment by dsyer** [comment]
Postgres is used in production (in the "production" and "staging" profiles) via a Cloudfoundry service.

**Comment by bclozel** [comment]
Closing as this question has been answered.
