### ISSUE TITLE
sagan gradle build fails on macOS Sierra v10.12.6

### ISSUE THREAD

**Issue by yaki123** [spring-io/sagan#881]
sagan gradle build fails on macOS Sierra v10.12.6

Ran command below and got the /Users/x7yv/GitHub/sagan/sagan-client/npm-debug.log
[npm-debug.log](https://github.com/spring-io/sagan/files/2793245/npm-debug.log)

**Comment by dsyer** [comment]
That's not really specific to your OS or version. The CI builds fail constantly, for instance. See e.g. #856.
