### ISSUE TITLE
https://projects.spring.io/spring-shell/ The '@ShellMethod' miss the open parenthesis

### ISSUE THREAD

**Issue by NOVA-ME** [spring-io/sagan#906]
![image](https://user-images.githubusercontent.com/18442141/58463723-f515ba80-8166-11e9-8ecb-a2e2107277b9.png)
Maybe we can change it to
 @ShellMethod(value = "Translate text from one language to another.")

**Comment by bclozel** [comment]
Could you create an issue or a PR on the spring-shell repository? This content is actually managed here: https://github.com/spring-projects/spring-shell/tree/gh-pages

**Comment by NOVA-ME** [comment]
> Could you create an issue or a PR on the spring-shell repository? This content is actually managed here: https://github.com/spring-projects/spring-shell/tree/gh-pages

Ok, I'll create a PR for them 👍
