### ISSUE TITLE
Failed to Run ./gradlew eclipse from root directory of sagan repository clone (Task 'eclipse' not found)

### ISSUE THREAD

**Issue by shahrk** [spring-io/sagan#909]
[stacktrace.txt](https://github.com/spring-io/sagan/files/3243569/stacktrace.txt)

* What went wrong:
Task 'eclipse' not found in root project 'sagan'.

**Comment by dsyer** [comment]
There is no eclipse task. You should use buildship to import into eclipse. Did you find a reference in the docs somewhere(maybe that needs to be fixed)?

**Comment by shahrk** [comment]
Yes this is the first step mentioned in the wiki for import to eclipse - https://github.com/spring-io/sagan/wiki/Import-into-IDEA-or-Eclipse

**Comment by dsyer** [comment]
Thanks. The wiki is out of date it seems.

**Comment by studytoohard** [comment]
1. open sagan-site/build.gradle
2. add ```'apply plugin: 'eclipse'``` at the last line

**Comment by dsyer** [comment]
No. The wiki is wrong. Please don't use the "eclipse" plugin.

**Comment by studytoohard** [comment]
so，what should I do to resolve this problem XD

**Comment by dsyer** [comment]
From comment above: "You should use buildship to import into eclipse". Spring Tool Suite comes with it pre-installed (for instance).

**Comment by bclozel** [comment]
I've just fixed the wiki page. Thanks for the report!

**Comment by studytoohard** [comment]
Thks，I will try this rigth now @dsyer
