### ISSUE TITLE
Typo in Spring Security Architecture Topical Guide

### ISSUE THREAD

**Issue by anno1985** [spring-io/sagan#924]
https://spring.io/guides/topicals/spring-security-architecture#_authorization_or_access_control

Reads: 
> An AccessDecisionVoter considers an Authentication (representing a principal) and a secure Object which as been decorated with ConfigAttributes:

Should read (as -> has):
> An AccessDecisionVoter considers an Authentication (representing a principal) and a secure Object which ***h***as been decorated with ConfigAttributes:

NB: Is there a way to raise typos directly as PR?

**Comment by bclozel** [comment]
Yes, the guide itself is actually a git repository (the link is displayed at the top of the right hand column). See https://github.com/spring-guides/top-spring-security-architecture

Could you raise an issue or a PR directly there?
Thanks!

**Comment by anno1985** [comment]
Done: https://github.com/spring-guides/top-spring-security-architecture/pull/11
