### ISSUE TITLE
Display current STS 4 version on the downloads page

### ISSUE THREAD

**Issue by kdvolder** [spring-io/sagan#925]
This is the page I am referring to:

https://spring.io/tools

The page has a bunch of links on it and downloads the latest version of STS 4. However, as a user I have no way of knowing, by looking at that page, what version I am actually downloading before actually downloading it.

It would be nice if the current version was displayed *somewhere* on the page, preferably somewhere prominently or close to the download links themselves. I.e. so that when I click on a download button I know exactly what version that button will actually download.

**Comment by rajsekharmahapatro** [comment]
The version you are going to download is mentioned well on the download link "Download STS4 Linux 64-bit", "Download STS4 MaxOs 64-bit"

**Comment by kdvolder** [comment]
>  "Download STS4 Linux 64-bit", "Download STS4 MaxOs 64-bit"

THat is not a version. A version would be something STS 4.4.1. It only tells you whether what OS you are downloading a build for. Each of those links is a different build of the same version.

**Comment by kdvolder** [comment]
I suggest the buttons could be labeled something like:

`Download STS 4.4.1 Linux 64-bit`, `Download STS 4.4.1 MaxOs 64-bit` etc.

4.4.1 is the current / latest version of STS. That number changes everytime we release a new version.

**Comment by martinlippert** [comment]
I could also imagine to display the version in the text above the buttons, so that the buttons stay the same and the version appears on top of them. Maybe that looks nicer from the design perspective. I would also be fine with manually configuring that version value in the admin/tools section via a specific field in order to avoid additional logic to parse the version from the file names that we specify for the downloads. The extra field would make this config value more explicit, too.

**Comment by martinlippert** [comment]
@bclozel Any thoughts on this? Would be awesome if we could add the version info to the tools page (in a very simple way, no automatic parsing or logic needed, I think).

**Comment by bclozel** [comment]
This is now live. Feel free to edit the new field in https://spring.io/admin/tools/

**Comment by martinlippert** [comment]
@bclozel First of all, many many many thanks for implementing this, so much appreciated. I entered the corresponding values already.

I am not sure whether the look on the website is exactly what I had in mind. To me the version information on https://spring.io/tools looks a bit inconsistent and slightly strange, which is also related to us having so different boxes for Eclipse-based distros, VSCode extensions, etc. I am inclined to think about some broader changes and improvements here... :-) Lets chat offline about that.
