### ISSUE TITLE
500 on missing/outdated guide

### ISSUE THREAD

**Issue by snicoll** [spring-io/sagan#933]
It looks like a missing guide is 500 again, see https://twitter.com/pSYoniK/status/1204312628312596482 and https://github.com/spring-io/sagan/issues/171

**Comment by JosejeSinohui** [comment]
Hi!, i can work on this

**Comment by dsyer** [comment]
By all means.

**Comment by JosejeSinohui** [comment]
I couldn't use hub to make the pull request since i don't have write access to the repo (I made a fork and did my commit there).

@snicoll @dsyer can any of you guys review it? thanks for your time :)

**Comment by dsyer** [comment]
Maybe use the GitHub UI to send a pull request?

**Comment by JosejeSinohui** [comment]
That's what i ended up doing, here is the link #934

**Comment by bclozel** [comment]
Closing in favor of #934
