### ISSUE TITLE
sagan-site:bootRun run  ERROR

### ISSUE THREAD

**Issue by boomwakalaka** [spring-io/sagan#937]
Hi, i found this error trying to build through the "gradlew :sagan-site:bootRun --debug" command 

> 22:23:58.026 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 6.358 secs
22:23:58.026 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':',5,main]] finished, busy: 6.326 secs, idle: 0.033 secs
22:23:58.026 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 2,5,main]] finished, busy: 0.0 secs, idle: 6.358 secs
22:23:58.027 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'22:23:58.028 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':sagan-client:npmInstall'.
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command 'C:\Users\Consul19\eclipse-sagam-workspace\sagan\sagan-client\.gradle\nodejs\node-v4.2.2-windows-x64\bin\node.exe'' finished with non-zero exit value 1
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org22:23:58.029 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
22:23:58.030 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 9s

> 

And this is the output without the "--debug" 

Configure project :sagan-site
For project [sagan-site] with version [1.0.0.BUILD-SNAPSHOT] the resolved Artifactory repo is [libs-snapshot-local]

Task :sagan-client:npmInstall
npm WARN package.json sagan@ No license field.
npm WARN prefer global npm@2.14.7 should be installed with -g

sagan@ prepublish C:\Users\Consul19\eclipse-sagam-workspace\sagan\sagan-client
 jspm install

"jspm" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

npm ERR! Windows_NT 10.0.18362
npm ERR! argv "C:\\Users\\Consul19\\eclipse-sagam-workspace\\sagan\\sagan-client\\.gradle\\nodejs\\node-v4.2.2-windows-x64\\bin\\node.exe" "C:\\Users\\Consul19\\eclipse-sagam-workspace\\sagan\\sagan-client\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! sagan@ prepublish: `jspm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sagan@ prepublish script 'jspm install'.
npm ERR! This is most likely a problem with the sagan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jspm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls sagan
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Consul19\eclipse-sagam-workspace\sagan\sagan-client\npm-debug.log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sagan-client:npmInstall'.
Process 'command 'C:\Users\Consul19\eclipse-sagam-workspace\sagan\sagan-client\.gradle\nodejs\node-v4.2.2-windows-x64\bin\node.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
3 actionable tasks: 1 executed, 2 up-to-date

> 

Can you help me? I read other issues but I couldn't find similar question like mine

**Comment by tiversusit** [comment]
Facing the same issue?

**Comment by bclozel** [comment]
We’ve removed jspm from the build so this issue no longer applies.
