### ISSUE TITLE
Add Index on member_profile.username to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [spring-io/sagan#942]
Missing index on table `member_profile` column `username` might make the underlying query issued via [TeamService#fetchMemberProfileUsername](https://github.com/spring-io/sagan/blob/68d9ced83d8ee97c7972a0d603a9077299c0435f/sagan-common/src/main/java/sagan/team/support/TeamService.java#L41) slow. Since table `member_profile` is mostly read by guests and sometimes inserted or updated by admin, the performance impact for write operations is acceptable under common cases.

**Comment by VikramjeetRaj** [comment]
I want to work on this issue, being a beginner can you please assign this and guide me through it.
