### ISSUE TITLE
Optimize Index to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [spring-io/sagan#967]
## Problem
Through our test, we found that adding index in some table can improve query efficiency, and some index which may make query slow need to be dropped.We will talk about them respectively.
### 1.member_profile
Add index on column **username** which will influence [TeamRepository#findByUsername](https://github.com/spring-io/sagan/blob/c72f0acdc9221c958b4e04f52b63b0df0565a759/sagan-common/src/main/java/sagan/team/support/TeamRepository.java#L19).  
Add index on column **github_id** which will influence [TeamRepository#findByGithubId](https://github.com/spring-io/sagan/blob/c72f0acdc9221c958b4e04f52b63b0df0565a759/sagan-common/src/main/java/sagan/team/support/TeamRepository.java#L17).
### 2.post
Add index on column **author_id** which is a foreign key refering to member_profile.id.  
Drop index on column **draft** which is boolean type with poor selectivity.
### 3.project
Add index on column **display_order** which will influence [ProjectMetadataService#sortByDisplayOrderAndId](https://github.com/spring-io/sagan/blob/c72f0acdc9221c958b4e04f52b63b0df0565a759/sagan-common/src/main/java/sagan/projects/support/ProjectMetadataService.java#L15).
### 1.Add Index
member_profile.username  
member_profile.github_id  
post.author_id  
project.display_order  
### 2.Drop Index
post.draft

**Comment by bclozel** [comment]
Closing in favor of #968
