### ISSUE TITLE
Hard-coded og:url in all Spring blog posts

### ISSUE THREAD

**Issue by richardfearn** [spring-io/sagan#974]
With the new website, all blog posts contain this HTML:

    <meta content="https://www.spring.io" property="og:url" />

which (I think) causes problems for sites that save articles for later reading (e.g. Instapaper). It makes it look as though every blog post has the same URL, so attempting to save any blog post (e.g. https://spring.io/blog/2020/02/14/announcing-the-new-spring-website) results in the home page (https://www.spring.io) being saved instead.

The `og:url` was added in 3b75b82.

**Comment by richardfearn** [comment]
@oodamien Thanks for looking at this so quickly!

Instapaper very kindly updated their parser to disregard the incorrect `og:url`, so it's possible to save Spring Blog articles to Instapaper now.

They also pointed me to this:

https://developers.facebook.com/tools/debug/

which does show up a warning for the blog articles.

Thanks again for looking into this!

**Comment by oodamien** [comment]
@richardfearn This PR https://github.com/spring-io/sagan/pull/975 should fix the issue.
I will make more tests with this tools.
Thanks!

**Comment by richardfearn** [comment]
Thank you!
