### ISSUE TITLE
Duplicate og:title in Spring blog posts

### ISSUE THREAD

**Issue by richardfearn** [spring-io/sagan#977]
Following on from #974 / #975, I think there's also an issue with the `og:title` property. For example:

https://spring.io/blog/2020/04/09/spring-graal-native-0-6-0-released

has this:

    <meta content="Spring" property="og:title" />

but further down has this:

    <meta property="og:title" content="Spring Graal Native 0.6.0 released" />

**Comment by bclozel** [comment]
This should be fixed by 53c826952886bf53c
Thanks!

**Comment by richardfearn** [comment]
Looks good - thank you!
