### ISSUE TITLE
Learn tab in the project page does not display versions using the new scheme correctly

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/sagan#981]
I've just updated Spring Boot's project metadata to add 2.4.0-SNAPSHOT. On the learn tab of the project page, the version is correctly tagged as `SNAPSHOT` but it's shown as `2.4`. I expected it to be `2.4.0`. I looked at the Spring Security page to see if it has a similar problem. There, 5.4.0-M1 is correctly labelled as `PRE` but the version is shown as `5.4 0-M1`.

**Comment by wilkinsona** [comment]
This seems to apply more broadly. The endpoint that start.spring.io uses is also affected as it is currently displaying 2.4.0 snapshots as 2.4 snapshots.

**Comment by bclozel** [comment]
Fixed with 70dd61aa51bb989d89cfd9e8aaaf5066cd4d0faa and 8ac8c7f1a161d86e3a927776d5b4a5bb68c78bb6
