### ISSUE TITLE
spring.io 404 Not Found: Requested route ('spring.io') does not exist.

### ISSUE THREAD

**Issue by donhuvy** [spring-io/sagan#982]
Error: 

404 Not Found: Requested route ('spring.io') does not exist.

![image](https://user-images.githubusercontent.com/1328316/83826497-3c357480-a706-11ea-956d-800b7cd3a09f.png)

In the same time, https://start.spring.io/ is normal.

![image](https://user-images.githubusercontent.com/1328316/83826544-5c653380-a706-11ea-9241-9d2a70f7be49.png)

![image](https://user-images.githubusercontent.com/1328316/83826681-b1a14500-a706-11ea-8110-caad06f27349.png)

**Comment by trevormarshall** [comment]
Thank you for the report. We are aware of the issue, see https://status.spring.io.

**Comment by bclozel** [comment]
This is fixed and stable now.
Thanks!
