### ISSUE TITLE
Question about admin panel

### ISSUE THREAD

**Issue by lokize** [spring-io/sagan#983]
how to use admin panel?

**Comment by lokize** [comment]
here is my build scan: https://scans.gradle.com/s/cvlo42elyhqmm

**Comment by lokize** [comment]
https://gradle.com/s/zomntblcvlzv2

**Comment by lokize** [comment]
thanks for reply, my problem is authenticate in admin panel, 
![image](https://user-images.githubusercontent.com/19701630/84497284-dc4e4900-ac84-11ea-9d6a-82079f618e38.png)

**Comment by dsyer** [comment]
Is this in your own instance of the site? You would have to configure it to authenticate a GitHub team/org that you are a member of. By default it only allows members of the Spring team.

**Comment by bclozel** [comment]
@lokize I believe you should find [the relevant information in our wiki here](https://github.com/spring-io/sagan/wiki/Manage-authentication-in-Sagan).
Thanks!
