### ISSUE TITLE
Do not display documentation links when not defined

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/sagan#993]
Spring Data project do not set documentation because this is a meta project, documentation lives in sub projects like Spring Data JPA, Spring Data JDBC, etc.
![image](https://user-images.githubusercontent.com/141109/89542994-ac44a180-d800-11ea-84d2-f21010af4a28.png)

The end result for end user is confusing because the related learn tab displays documentation links pointing to https://spring.io/projects/spring-data.
![image](https://user-images.githubusercontent.com/141109/89543143-dc8c4000-d800-11ea-8c02-0eee63cedacb.png)

I think the correct behavior would be to not display the "Reference Doc." and "API Doc." links if not set.

**Comment by mp911de** [comment]
FTR, we receive questions from the community about misleading links.

https://twitter.com/dr_pompeii/status/1324394291280678912

**Comment by manueljordan** [comment]
If is not possible remove the current links due the template

I think the current paragraph


>Each Spring project has its own; it explains in great details how you can use project features and what you can achieve with them.

Would be changed to:

>Each Spring project has its own 'Reference Documentation' and 'API Doc'; it explains in great details how you can use project features and what you can achieve with them. Please ignore the current links shown just below.

**Comment by bclozel** [comment]
Links are not displayed if the releases don't have any link info for the API docs or ref docs.
We can still improve the "Documentation" section, but I guess this fix is good enough for now.

**Comment by manueljordan** [comment]
Thanks for the info.
