### ISSUE TITLE
I use springboot rest api to response a image,if set MediaType.IMAGE_JPEG_VALUE  will be request twice，method invoke twice

### ISSUE THREAD

**Issue by Charlie89757** [spring-io/sagan#996]
I use springboot rest api to response a image,if set MediaType.IMAGE_JPEG_VALUE  will be request twice，method invoke twice

**Comment by bclozel** [comment]
Please use StackOverflow for general questions about Spring Boot, this issue tracker is dedicated to the spring.io application.
Thanks!
