### ISSUE TITLE
Some guides are not rendering

### ISSUE THREAD

**Issue by kdvolder** [spring-io/sagan#999]
I have no idea of the scope of this problem, nor the cause, nor whether it is a temporary issue or not. Bot some of the guides do not display any content.

For example: https://spring.io/guides/gs/accessing-data-jpa/

I can still find the guide via google or via the https://spring.io/guides/ page (search for jpa). But when I go to the actual guide there's no content there (just the header and footers we see on every page but no tutorial contents). Most of the other guides I tried to go to do work, but there was at least one other guide that didn't. Sorry I do not remember which one it was, I clicked on a few.

**Comment by gregturn** [comment]
I tried clearing the caches but it didn’t help.
